# DNN Assignment
In this assignment you are working together with your teammates from the second project. You will apply your new knowledge about dense neural networks to the data from your ML project to investigate, if you can make further improvements on prediction performance. Your data is (hopefully) already cleaned and transformed (this was part of your ML project) such that you can focus fully on feeding it to your neural network. Use TensorFlow 2.x in this assignment as it makes training with real-life data much more easier with many implemented features (e.g. early-stopping, tensorboard, regularization, etc.). 

In this notebook you will learn
- how to apply a neural network to your own data using TensorFlow 2.x
- how to tune the network and monitor learning
- how to train several networks and ensemble them into a stronger model

# Neuer Abschnitt

# Neuer Abschnitt

# Module loading
Load all the necessary packages for your assignment. We give you some modules in advance, feel free to add more, if you need them.

In [12]:
import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt

from tensorflow.keras import layers
from tensorflow.keras import regularizers
    
print('Using TensorFlow version: %s' % tf.__version__)
import os

from sklearn.metrics import confusion_matrix, classification_report

Using TensorFlow version: 2.5.0


In [13]:
#!pip install -q git+https://github.com/tensorflow/docs
    
import tensorflow_docs as tfdocs
import tensorflow_docs.modeling
import tensorflow_docs.plots

## Data loading
Load here your data from your ML project. You can use either `pandas` or `numpy` to format your data. 

In [30]:
# Load data
from google.colab import files


X_train = pd.read_csv("https://raw.githubusercontent.com/amStraszenrand/NeueFische-2nd_Project/main/X_train.csv",index_col=0)
X_test = pd.read_csv("https://raw.githubusercontent.com/amStraszenrand/NeueFische-2nd_Project/main/X_test.csv",index_col=0)
y_train = pd.read_csv("https://raw.githubusercontent.com/amStraszenrand/NeueFische-2nd_Project/main/y_train.csv",index_col=0)
y_test = pd.read_csv("https://raw.githubusercontent.com/amStraszenrand/NeueFische-2nd_Project/main/y_test.csv",index_col=0)



## Training
For training you need a train/val split (hopefully you did a train/test split before (and you should use the same as in your ML project to make results comparable). 

In [48]:
#N_VAL = 
#N_TRAIN = 
#BATCH_SIZE = 
#STEPS_PER_EPOCH = N_TRAIN // BATCH_SIZE
#EPOCHS = 




# Define dictionary to store results
training_history = {}

# Define number of epochs and learning rate decay
N_TRAIN = len(X_train)
EPOCHS = 200
BATCH_SIZE = 320
STEPS_PER_EPOCH = N_TRAIN // BATCH_SIZE
lr_schedule = tf.keras.optimizers.schedules.InverseTimeDecay(
    0.01,
    decay_steps=STEPS_PER_EPOCH*1000,
    decay_rate=1,
    staircase=False)


# Define optimizer used for modelling
optimizer = tf.keras.optimizers.Adagrad(learning_rate=lr_schedule, name='Adagrad', )

In [32]:
X_train.shape

(91302, 40)

In [33]:
# Define model architecture in function
def get_compiled_small_model():
    small_model = tf.keras.Sequential([
      tf.keras.layers.Dense(16,kernel_initializer = 'uniform', activation='relu', input_dim = 40),
      tf.keras.layers.Dense(16,kernel_initializer = 'uniform', activation='relu'),
      tf.keras.layers.Dense(1,kernel_initializer = 'uniform', activation= "sigmoid")
    ])

    small_model.compile(optimizer="adam",
                  loss='binary_crossentropy',
                  metrics=['accuracy'])
    return small_model

### Build, compile and fit your model
To become fast at retraining your (different) models it is good practice to define a function that gets fed by a model, its name, an optimizer to use and the number of epochs you want the model to be trained. 

If your model trains for many epochs you will receive a lot of logging from TensorFlow. To reduce the logging noise you can use a callback (provided by the `tensorflow_docs` module we installed and imported for you) named `EpochDots()` that simply prints a `.` for each epoch and a full set of metrics after a number of epochs have been trained. 

If you want to produce logs for using Tensorboard you also need to include the `callbacks.Tensorboard()`.

In [34]:
#def get_callbacks():


# Define path where checkpoints should be stored
checkpoint_path = "training_1/cp.ckpt"
checkpoint_dir = os.path.dirname(checkpoint_path)

# Create a callback that saves the model's weights
cp_callback = tf.keras.callbacks.ModelCheckpoint(filepath=checkpoint_path,
                                                 save_weights_only=True,
                                                 verbose=0) # Set verbose != 0 if you want output during training



# return [list of your callbacks]

In [35]:
# Instantiate small model and print model summary
small_model = get_compiled_small_model()
print(small_model.summary())

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 16)                656       
_________________________________________________________________
dense_4 (Dense)              (None, 16)                272       
_________________________________________________________________
dense_5 (Dense)              (None, 1)                 17        
Total params: 945
Trainable params: 945
Non-trainable params: 0
_________________________________________________________________
None


In [29]:
X_train

Unnamed: 0  loan_amnt  ...  purpose_vacation  purpose_wedding
0           78397   0.266522  ...                 0                0
1           24562   0.046377  ...                 0                0
2           94716   0.399996  ...                 0                0
3           43236   0.136544  ...                 0                0
4           11434   0.057971  ...                 0                0
...           ...        ...  ...               ...              ...
91297       23410   0.275362  ...                 0                0
91298       62737   0.176027  ...                 0                0
91299       20590   0.217391  ...                 0                0
91300       89710   0.380082  ...                 0                0
91301      105493   0.532542  ...                 0                0

[91302 rows x 41 columns]

In [36]:
training_history['small'] = small_model.fit(X_train,
                     y_train,
                     validation_split=0.2,
                     verbose=5,
                     steps_per_epoch=STEPS_PER_EPOCH,
                     epochs=EPOCHS)

Epoch 1/500
Epoch 2/500
Epoch 3/500
Epoch 4/500
Epoch 5/500
Epoch 6/500
Epoch 7/500
Epoch 8/500
Epoch 9/500
Epoch 10/500
Epoch 11/500
Epoch 12/500
Epoch 13/500
Epoch 14/500
Epoch 15/500
Epoch 16/500
Epoch 17/500
Epoch 18/500
Epoch 19/500
Epoch 20/500
Epoch 21/500
Epoch 22/500
Epoch 23/500
Epoch 24/500
Epoch 25/500
Epoch 26/500
Epoch 27/500
Epoch 28/500
Epoch 29/500
Epoch 30/500
Epoch 31/500
Epoch 32/500
Epoch 33/500
Epoch 34/500
Epoch 35/500
Epoch 36/500
Epoch 37/500
Epoch 38/500
Epoch 39/500
Epoch 40/500
Epoch 41/500
Epoch 42/500
Epoch 43/500
Epoch 44/500
Epoch 45/500
Epoch 46/500
Epoch 47/500
Epoch 48/500
Epoch 49/500
Epoch 50/500
Epoch 51/500
Epoch 52/500
Epoch 53/500
Epoch 54/500
Epoch 55/500
Epoch 56/500
Epoch 57/500
Epoch 58/500
Epoch 59/500
Epoch 60/500
Epoch 61/500
Epoch 62/500
Epoch 63/500
Epoch 64/500
Epoch 65/500
Epoch 66/500
Epoch 67/500
Epoch 68/500
Epoch 69/500
Epoch 70/500
Epoch 71/500
Epoch 72/500
Epoch 73/500
Epoch 74/500
Epoch 75/500
Epoch 76/500
Epoch 77/500
Epoch 78

In [37]:
y_pred_sm = small_model.predict(X_test).round()
y_pred_sm_train = small_model.predict(X_train).round()

In [38]:
y_pred_sm

array([[1.],
       [0.],
       [1.],
       ...,
       [0.],
       [0.],
       [1.]], dtype=float32)

In [39]:
print(confusion_matrix(y_train,y_pred_sm_train))
print(classification_report(y_train,y_pred_sm_train))

[[30368 15307]
 [ 8143 37484]]
              precision    recall  f1-score   support

           0       0.79      0.66      0.72     45675
           1       0.71      0.82      0.76     45627

    accuracy                           0.74     91302
   macro avg       0.75      0.74      0.74     91302
weighted avg       0.75      0.74      0.74     91302



In [40]:
print(confusion_matrix(y_test,y_pred_sm))
print(classification_report(y_test,y_pred_sm))

[[5962 3066]
 [ 788  627]]
              precision    recall  f1-score   support

           0       0.88      0.66      0.76      9028
           1       0.17      0.44      0.25      1415

    accuracy                           0.63     10443
   macro avg       0.53      0.55      0.50     10443
weighted avg       0.79      0.63      0.69     10443



In [ ]:
# Plotting function for loss
def plot_loss(history):
    plt.plot(history.history['accuracy'], label='accuracy')
    plt.plot(history.history['val_accuracy'], label='val_accuracy')
    plt.title('Model Accuracy')
    plt.ylim([0, 10])
    plt.xlabel('Epoch')
    plt.ylabel('Error')
    plt.legend()
    plt.grid(True)

In [ ]:
# Plotting function for MSE
def plot_metric(history):
    plt.plot(history.history['hinge'])
    plt.plot(history.history['val_hinge'])
    plt.title('Model HINGE')
    plt.ylabel('HINGE')
    plt.xlabel('Epoch')
    plt.legend(['train', 'validation'], loc='upper right')
    plt.show()


In [ ]:
# plot MSE history 
plot_metric(training_history['small'])

# Plot loss history
plot_loss(training_history['small'])


KeyError: 'hinge'

You can implement your callbacks in the `model.fit()` method below.

In [ ]:
#def model_compile_and_fit(model, name, optimizer=None, max_epochs=30):
    # Get optimizer
    
    # model.compile
    
    # model.fit
    
    # return results

#### Build your model
You can build your model by using `tf.keras.Sequential()` that helps you to sequentially define your different layers from input to output. 

In [ ]:
#your_model = tf.keras.Sequential([
#    layers.Dense(),
#    layers.Dense()
#])    

#### Train your model
Train your model by using your `model_compile_and_fit()` function you defined above.

In [ ]:
#your_history = model_compile_and_fit(your_model, ....)

#### Evaluate your model training
TensorFlow offers now (this was more cumbersome before) a simple history plotter that you can use to plot training histories and see how the model performed on training and validation data set.

# Neuer Abschnitt

In [ ]:
# history_plotter = tfdocs.plots.HistoryPlotter(metric = 'your_metric', smoothing_std=10)
# history_plotter.plot(your_history)

## Model tuning
You might have no luck with your first model (most surely you did not). In this section you will apply methods you know to tune your model's performance. An obvious way of course is to change your model's architecture (removing or adding layers or layer dimensions, changing activation functions). 

However, after this you might still be able to detect some overfitting and there are some more methods you can apply to improve your neural network. Some of them are regularization, learning rate decay, early stopping, or dropout. 

If you want to add regularization you can apply directly layer-wise L2- or L1-regularization by using a layer's `kernel_regularization` argument and an appropriate regularizer from the [`tensorflow.keras.regularizers`](https://www.tensorflow.org/api_docs/python/tf/keras/regularizers) module we imported for you.  

__Optimizer schedules__<br>
Quite often your optimizer does not run efficiently through the loss function surface. Remember that theory ensures a convergence of mini-batch SGD if and only if the learing rate decreases sufficiently fast. A way to apply this to your model training is to use a learning rate scheduler (learning rate decay) that reduces the learning rate over the number of update steps. The [`tf.keras.optimizers.schedules`](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/schedules) module offers you some approaches to do that. 

Note that to apply this to your `model_compile_and_fit()` function you defined above you need to implement the learning rate schedule either in there or with a helper function that your function calls inside. 

If you want to visualize different schedulers you can define them and call them on a range of values and plot them in a line plot. 

__Early stopping__<br>
Earyl stopping is a procedure that enables you to stop your training earlier than defined by your `max_epochs` argument. It is used in practices to 
1. determine the optimal parameter vector by monitoring the validation error closely (if it rises again too much stuck with the best parameters found until then) and
2. to save expensive resources (either in terms of monetary costs or ecological costs).

To implement early stopping in TensorFlow the `tf.keras` module offers you a `callback` named [`tf.keras.callback.EarlyStopping()`](https://www.tensorflow.org/api_docs/python/tf/keras/callbacks/EarlyStopping) that monitors for you a certain metric (it makes sense here to use a validation metric) and to stop training after a certain number of epochs with no improvement or by defining a certain `min_delta` that defines a minimum value of improvement - if below the callback stops your training. 

You can add this callback simply to the callbacks defined in your `get_callbacks()` function you defined above.

__Dropout__<br>
Dropout was one of the important developments in regularization for neural networks. It was developed by Geoffrey Hinton and his team at Toronto University. 

Dropout can be applied to each layer in your network and is implemented in `tf.keras` by an own layer named `Dropout()` awaiting a dropout rate set by you. So to introduce dropout you have to rework your model design.  

Make use of your knowledge and apply tuning techniques to improve your network. 

# Neuer Abschnitt

# Neuer Abschnitt

# Neuer Abschnitt

In [49]:
# Define model architecture in function
def get_compiled_middle_model_dropout():
    middle_drop = tf.keras.Sequential([
      tf.keras.layers.Dense(30,kernel_initializer = 'uniform', activation='relu', input_dim = 40,kernel_regularizer=regularizers.l2(0.01)),
      tf.keras.layers.Dropout(0.25),
      tf.keras.layers.Dense(30,kernel_initializer = 'uniform', activation='relu',kernel_regularizer=regularizers.l2(0.01)),
      tf.keras.layers.Dropout(0.25),
      tf.keras.layers.Dense(30,kernel_initializer = 'uniform', activation='relu',kernel_regularizer=regularizers.l2(0.01)),
      tf.keras.layers.Dropout(0.25),
      tf.keras.layers.Dense(1,kernel_initializer = 'uniform', activation= "sigmoid")
    ])

    middle_drop.compile(optimizer="adam",
                  loss='binary_crossentropy',
                  metrics=['accuracy'])
    return middle_drop

In [50]:
#===========#
# YOUR CODE #
#===========#

# Instantiate small model and print model summary
middle_model = get_compiled_middle_model_dropout()
print(middle_model.summary())

training_history['small'] = small_model.fit(X_train,
                     y_train,
                     validation_split=0.2,
                     verbose=5,
                     steps_per_epoch=STEPS_PER_EPOCH,
                     epochs=EPOCHS)

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_14 (Dense)             (None, 30)                1230      
_________________________________________________________________
dropout_6 (Dropout)          (None, 30)                0         
_________________________________________________________________
dense_15 (Dense)             (None, 30)                930       
_________________________________________________________________
dropout_7 (Dropout)          (None, 30)                0         
_________________________________________________________________
dense_16 (Dense)             (None, 30)                930       
_________________________________________________________________
dropout_8 (Dropout)          (None, 30)                0         
_________________________________________________________________
dense_17 (Dense)             (None, 1)                

## Model ensembling
You have learned that models can be ensembled. What is possible in `scikit-learn` is also possible in TensorFlow, just a little different as it is relying on its computation graph. However, any model is callable like a `layer` by invoking it on either an `Input` or on the output of another layer. Furthermore, you can also stack outputs together.

To produce an ensemble you can define a couple of models, than use their predictions as inputs for another model and produce a final output (using `keras.Model(input, output)`). But you can also start simple and use the mean predictions over all models and then compute the `argmax()` to assign them to a class in classification (via using `layers.average([model1_preds,model2_preds,...])`). You will be surprised how well this works. 

Now implement your own ensemble to improve your work even a little more and to have something more to polish up your ML project on `GitHub` ;) 

In [51]:
y_pred_m_dropout = middle_model.predict(X_test).round()
y_pred_m_dropout_train = middle_model.predict(X_train).round()

In [52]:
print(confusion_matrix(y_train,y_pred_m_dropout_train))
print(classification_report(y_train,y_pred_m_dropout_train))

[[24493 21182]
 [25330 20297]]
              precision    recall  f1-score   support

           0       0.49      0.54      0.51     45675
           1       0.49      0.44      0.47     45627

    accuracy                           0.49     91302
   macro avg       0.49      0.49      0.49     91302
weighted avg       0.49      0.49      0.49     91302



In [53]:
#===========#
# YOUR CODE #
#===========#
print(confusion_matrix(y_test,y_pred_m_dropout))
print(classification_report(y_test,y_pred_m_dropout))

[[4816 4212]
 [ 771  644]]
              precision    recall  f1-score   support

           0       0.86      0.53      0.66      9028
           1       0.13      0.46      0.21      1415

    accuracy                           0.52     10443
   macro avg       0.50      0.49      0.43     10443
weighted avg       0.76      0.52      0.60     10443

