In [27]:
%store -r X_train X_test y_grade_train y_grade_test

y_train = y_grade_train
y_test = y_grade_test

In [28]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import svm

from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import LinearSVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, classification_report


In [29]:
##### Funktion to printe the scores
def score_print(y,y_pred):
    
    cm = confusion_matrix(y,y_pred)
    print(cm)
    cp= classification_report(y,y_pred)
    print(cp)
    

In [30]:
grades = pd.DataFrame(y_train.value_counts())


In [31]:
###### Naiv-estimator

# TODO: Total number of records
n_records = len(y_train)

# TODO: Different grades
grades = pd.DataFrame(y_train.value_counts())

# TODO: Mmost frequent grade 
most_frequent_grade = grades[grades["grade"] == int(grades.max())].index.tolist()[0]

# TODO: Percentage of individuals whose income is more than $50,000
percent = float(100 * grades.max() / n_records)

# Print the results
print ("Total number of records: {}".format(n_records))
print ("Individuals have grades: {}".format(grades))
print ("Individuals have most likely grade: {}".format(most_frequent_grade))
print ("Individuals have most likely grade with percent: {:.2f}%".format(percent))

Total number of records: 31901
Individuals have grades:    grade
B   9291
A   7638
C   6554
D   4512
E   2545
F    976
G    385
Individuals have most likely grade: B
Individuals have most likely grade with percent: 29.12%


In [32]:
####fit von log reg

lr = LogisticRegression(max_iter=10000, C = 2.0, random_state=70)
lr.fit(X_train, y_train)
lr.score(X_train, y_train)
y_pred = lr.predict(X_test)
score_print(y_test,y_pred)

ValueError: Found input variables with inconsistent numbers of samples: [54168, 31901]

In [25]:
score_print(y_train,lr.predict(X_train))

[[7384  254    0    0    0    0    0]
 [ 195 8684  412    0    0    0    0]
 [   3  488 5773  290    0    0    0]
 [   2    0  617 3702  191    0    0]
 [   4    0    0  749 1786    6    0]
 [   0    0    0    4  566  393   13]
 [   0    0    0    0   16  252  117]]
              precision    recall  f1-score   support

           A       0.97      0.97      0.97      7638
           B       0.92      0.93      0.93      9291
           C       0.85      0.88      0.86      6554
           D       0.78      0.82      0.80      4512
           E       0.70      0.70      0.70      2545
           F       0.60      0.40      0.48       976
           G       0.90      0.30      0.45       385

    accuracy                           0.87     31901
   macro avg       0.82      0.72      0.74     31901
weighted avg       0.87      0.87      0.87     31901

