In [119]:
%store -r X_train X_test y_grade_train y_grade_test

y_train = y_grade_train
y_test = y_grade_test

In [120]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import svm

from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import LinearSVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, classification_report, roc_auc_score


In [121]:
##### Funktion to printe the scores
def score_print(y,y_pred):
    
    cm = confusion_matrix(y,y_pred)
    print(cm)
    cp= classification_report(y,y_pred)
    print(cp)
    #roc = roc_auc_score(y, y_pred)
    #print(roc)
    

In [122]:
###### Naiv-estimator

# TODO: Total number of records
n_records = len(y_train)

# TODO: Different grades
grades = pd.DataFrame(y_train.value_counts())

# TODO: Mmost frequent grade 
most_frequent_grade = grades[grades[0] == int(grades.max())].index.tolist()[0]

# TODO: Percentage of individuals whose income is more than $50,000
percent = float(100 * grades.max() / n_records)

# Print the results
print ("Total number of records: {}".format(n_records))
print ("Individuals have grades: {}".format(grades))
print ("Individuals have most likely grade: {}".format(most_frequent_grade))
print ("Individuals have most likely grade with percent: {:.2f}%".format(percent))

Total number of records: 114128
Individuals have grades:        0
F  16304
B  16304
D  16304
A  16304
E  16304
G  16304
C  16304
Individuals have most likely grade: F
Individuals have most likely grade with percent: 14.29%


In [123]:
####fit von log reg

lr = LogisticRegression(max_iter=10000, C = 2.0, random_state=70)
lr.fit(X_train, y_train)

y_grade_pred_lr_test = lr.predict(X_test)
score_print(y_test,y_grade_pred_lr_test)

[[2476   69    0    0    0    0    0]
 [  71 2843  182    0    0    0    0]
 [   0  102 1884  197    0    0    0]
 [   2    0  143 1200  158    0    0]
 [   0    0    0  129  608  111    0]
 [   0    0    0    0   46  235   44]
 [   0    0    0    0    0   20  107]]
              precision    recall  f1-score   support

           A       0.97      0.97      0.97      2545
           B       0.94      0.92      0.93      3096
           C       0.85      0.86      0.86      2183
           D       0.79      0.80      0.79      1503
           E       0.75      0.72      0.73       848
           F       0.64      0.72      0.68       325
           G       0.71      0.84      0.77       127

    accuracy                           0.88     10627
   macro avg       0.81      0.83      0.82     10627
weighted avg       0.88      0.88      0.88     10627



In [124]:
########## score auf unsere trainingdaten
y_grade_pred_lr_train = lr.predict(X_train)

score_print(y_train,y_grade_pred_lr_train)

[[15990   314     0     0     0     0     0]
 [  299 15165   840     0     0     0     0]
 [    4   594 14749   957     0     0     0]
 [    2     1   861 14107  1333     0     0]
 [   15    12     6  1307 13492  1472     0]
 [    0     0     0     0  1624 13275  1405]
 [    0     0     0     0     0  1414 14890]]
              precision    recall  f1-score   support

           A       0.98      0.98      0.98     16304
           B       0.94      0.93      0.94     16304
           C       0.90      0.90      0.90     16304
           D       0.86      0.87      0.86     16304
           E       0.82      0.83      0.82     16304
           F       0.82      0.81      0.82     16304
           G       0.91      0.91      0.91     16304

    accuracy                           0.89    114128
   macro avg       0.89      0.89      0.89    114128
weighted avg       0.89      0.89      0.89    114128



In [125]:
%store y_grade_pred_lr_train y_grade_pred_lr_test

Stored 'y_grade_pred_lr_train' (ndarray)
Stored 'y_grade_pred_lr_test' (ndarray)


In [126]:
######## DecisionTree

dtc = DecisionTreeClassifier(max_depth=10, min_samples_split=5, random_state=70)
dtc.fit(X_train,y_train)
y_grade_pred_dtc_test=dtc.predict(X_test)
score_print(y_test,y_grade_pred_dtc_test)

[[2541    2    0    0    2    0    0]
 [   0 3093    3    0    0    0    0]
 [   0    5 2170    8    0    0    0]
 [   0    1    9 1476   14    3    0]
 [   0    0    0   48  774   26    0]
 [   0    0    0    0   10  298   17]
 [   0    0    0    0    0   11  116]]
              precision    recall  f1-score   support

           A       1.00      1.00      1.00      2545
           B       1.00      1.00      1.00      3096
           C       0.99      0.99      0.99      2183
           D       0.96      0.98      0.97      1503
           E       0.97      0.91      0.94       848
           F       0.88      0.92      0.90       325
           G       0.87      0.91      0.89       127

    accuracy                           0.99     10627
   macro avg       0.95      0.96      0.96     10627
weighted avg       0.99      0.99      0.99     10627



In [114]:
########## score auf unsere trainingdaten
y_grade_pred_dtc_train = dtc.predict(X_train)
score_print(y_train,y_grade_pred_dtc_train)

[[16306     0     0     0     0     0     0]
 [    1 16274    31     0     0     0     0]
 [    1    63 15818   424     0     0     0]
 [    1     1   178 15548   578     0     0]
 [    1     3     1   605 15084   612     0]
 [    0     0     0     0   762 14885   659]
 [    0     0     0     0     0   531 15775]]
              precision    recall  f1-score   support

           A       1.00      1.00      1.00     16306
           B       1.00      1.00      1.00     16306
           C       0.99      0.97      0.98     16306
           D       0.94      0.95      0.95     16306
           E       0.92      0.93      0.92     16306
           F       0.93      0.91      0.92     16306
           G       0.96      0.97      0.96     16306

    accuracy                           0.96    114142
   macro avg       0.96      0.96      0.96    114142
weighted avg       0.96      0.96      0.96    114142



In [115]:
%store y_grade_pred_dtc_train y_grade_pred_dtc_test

Stored 'y_grade_pred_dtc_train' (ndarray)
Stored 'y_grade_pred_dtc_test' (ndarray)


In [116]:
##### RandomForestClassifier

rfc= RandomForestClassifier(max_depth=10,min_samples_split=7)
rfc.fit(X_train,y_train)
y_grade_pred_rfc_test=rfc.predict(X_test)
score_print(y_test,y_grade_pred_rfc_test)

[[2491   54    0    0    0    0    0]
 [  63 2998   37    0    0    0    0]
 [   1  168 1838  178    1    0    0]
 [   2    8  143 1177  166    5    3]
 [   1    0   11  214  558   57    8]
 [   0    0    0   18   43  224   40]
 [   0    0    0    4    4   19  100]]
              precision    recall  f1-score   support

           A       0.97      0.98      0.98      2545
           B       0.93      0.97      0.95      3098
           C       0.91      0.84      0.87      2186
           D       0.74      0.78      0.76      1504
           E       0.72      0.66      0.69       849
           F       0.73      0.69      0.71       325
           G       0.66      0.79      0.72       127

    accuracy                           0.88     10634
   macro avg       0.81      0.81      0.81     10634
weighted avg       0.88      0.88      0.88     10634



In [117]:
########## score auf unsere trainingdaten
y_grade_pred_rfc_train =rfc.predict(X_train)
score_print(y_train,y_grade_pred_rfc_train)

[[16137   169     0     0     0     0     0]
 [  200 16051    55     0     0     0     0]
 [    4   788 14429  1074    10     1     0]
 [    3    25   965 14112  1184    16     1]
 [    9     3    86  2696 12688   769    55]
 [    0     0    22   822   935 13623   904]
 [    0     0    12   233   162   475 15424]]
              precision    recall  f1-score   support

           A       0.99      0.99      0.99     16306
           B       0.94      0.98      0.96     16306
           C       0.93      0.88      0.91     16306
           D       0.75      0.87      0.80     16306
           E       0.85      0.78      0.81     16306
           F       0.92      0.84      0.87     16306
           G       0.94      0.95      0.94     16306

    accuracy                           0.90    114142
   macro avg       0.90      0.90      0.90    114142
weighted avg       0.90      0.90      0.90    114142



In [118]:
%store y_grade_pred_rfc_train y_grade_pred_rfc_test

Stored 'y_grade_pred_rfc_train' (ndarray)
Stored 'y_grade_pred_rfc_test' (ndarray)
