In [56]:
%store -r X_train X_test y_grade_train y_grade_test

y_train = y_grade_train
y_test = y_grade_test

In [57]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import svm

from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import LinearSVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, classification_report


In [58]:
##### Funktion to printe the scores
def score_print(y,y_pred):
    
    cm = confusion_matrix(y,y_pred)
    print(cm)
    cp= classification_report(y,y_pred)
    print(cp)
    

In [59]:
grades = pd.DataFrame(y_train.value_counts())
grades

0
G  8335
E  8254
B  8115
A  8104
D  8103
C  8101
F  8059

In [60]:
###### Naiv-estimator

# TODO: Total number of records
n_records = len(y_train)

# TODO: Different grades
grades = pd.DataFrame(y_train.value_counts())

# TODO: Mmost frequent grade 
most_frequent_grade = grades[grades[0] == int(grades.max())].index.tolist()[0]

# TODO: Percentage of individuals whose income is more than $50,000
percent = float(100 * grades.max() / n_records)

# Print the results
print ("Total number of records: {}".format(n_records))
print ("Individuals have grades: {}".format(grades))
print ("Individuals have most likely grade: {}".format(most_frequent_grade))
print ("Individuals have most likely grade with percent: {:.2f}%".format(percent))

Total number of records: 57071
Individuals have grades:       0
G  8335
E  8254
B  8115
A  8104
D  8103
C  8101
F  8059
Individuals have most likely grade: G
Individuals have most likely grade with percent: 14.60%


In [61]:
####fit von log reg

lr = LogisticRegression(max_iter=10000, C = 2.0, random_state=70)
lr.fit(X_train, y_train)
lr.score(X_train, y_train)
y_pred = lr.predict(X_test)
score_print(y_test,y_pred)

[[2467   78    0    0    0    0    0]
 [  74 2842  182    0    0    0    0]
 [   1  114 1864  207    0    0    0]
 [   2    0  144 1180  178    0    0]
 [   1    0    0  113  638   97    0]
 [   0    0    0    0   46  241   38]
 [   0    0    0    0    0   22  105]]
              precision    recall  f1-score   support

           A       0.97      0.97      0.97      2545
           B       0.94      0.92      0.93      3098
           C       0.85      0.85      0.85      2186
           D       0.79      0.78      0.79      1504
           E       0.74      0.75      0.75       849
           F       0.67      0.74      0.70       325
           G       0.73      0.83      0.78       127

    accuracy                           0.88     10634
   macro avg       0.81      0.83      0.82     10634
weighted avg       0.88      0.88      0.88     10634



In [62]:
########## score auf unsere trainingdaten

score_print(y_train,lr.predict(X_train))

[[7961  143    0    0    0    0    0]
 [ 148 7585  382    0    0    0    0]
 [   2  269 7346  484    0    0    0]
 [   0    0  441 6916  746    0    0]
 [   0    1    0  689 6765  799    0]
 [   0    0    0    0  907 6369  783]
 [   0    0    0    0    0  639 7696]]
              precision    recall  f1-score   support

           A       0.98      0.98      0.98      8104
           B       0.95      0.93      0.94      8115
           C       0.90      0.91      0.90      8101
           D       0.85      0.85      0.85      8103
           E       0.80      0.82      0.81      8254
           F       0.82      0.79      0.80      8059
           G       0.91      0.92      0.92      8335

    accuracy                           0.89     57071
   macro avg       0.89      0.89      0.89     57071
weighted avg       0.89      0.89      0.89     57071



In [63]:
######## DecisionTree

dtc = DecisionTreeClassifier(max_depth=10, min_samples_split=5, random_state=70)
dtc.fit(X_train,y_train)
y_pred_dtc=dtc.predict(X_test)
score_print(y_test,y_pred_dtc)

[[2542    3    0    0    0    0    0]
 [   1 3095    2    0    0    0    0]
 [   1    6 2129   50    0    0    0]
 [   2    0    9 1473   20    0    0]
 [   0    0    1   56  788    4    0]
 [   0    0    0    0   12  304    9]
 [   0    0    0    0    0   10  117]]
              precision    recall  f1-score   support

           A       1.00      1.00      1.00      2545
           B       1.00      1.00      1.00      3098
           C       0.99      0.97      0.98      2186
           D       0.93      0.98      0.96      1504
           E       0.96      0.93      0.94       849
           F       0.96      0.94      0.95       325
           G       0.93      0.92      0.92       127

    accuracy                           0.98     10634
   macro avg       0.97      0.96      0.96     10634
weighted avg       0.98      0.98      0.98     10634



In [64]:
########## score auf unsere trainingdaten
 
score_print(y_train,dtc.predict(X_train))

[[8104    0    0    0    0    0    0]
 [   4 8094   17    0    0    0    0]
 [   0   34 7828  239    0    0    0]
 [   0    0   76 7792  235    0    0]
 [   0    0    0  330 7577  347    0]
 [   0    0    0    0  309 7481  269]
 [   0    0    0    0    0  294 8041]]
              precision    recall  f1-score   support

           A       1.00      1.00      1.00      8104
           B       1.00      1.00      1.00      8115
           C       0.99      0.97      0.98      8101
           D       0.93      0.96      0.95      8103
           E       0.93      0.92      0.93      8254
           F       0.92      0.93      0.92      8059
           G       0.97      0.96      0.97      8335

    accuracy                           0.96     57071
   macro avg       0.96      0.96      0.96     57071
weighted avg       0.96      0.96      0.96     57071



In [65]:
##### RandomForestClassifier

rfc= RandomForestClassifier(max_depth=10,min_samples_split=7)
rfc.fit(X_train,y_train)
y_pred_rfc=rfc.predict(X_test)
score_print(y_test,y_pred_rfc)

[[2488   57    0    0    0    0    0]
 [  69 3009   20    0    0    0    0]
 [   1  179 1837  162    6    1    0]
 [   2    9  143 1093  251    6    0]
 [   1    0    7  205  584   50    2]
 [   0    0    0   18   44  219   44]
 [   0    0    0    4    3   15  105]]
              precision    recall  f1-score   support

           A       0.97      0.98      0.97      2545
           B       0.92      0.97      0.95      3098
           C       0.92      0.84      0.88      2186
           D       0.74      0.73      0.73      1504
           E       0.66      0.69      0.67       849
           F       0.75      0.67      0.71       325
           G       0.70      0.83      0.76       127

    accuracy                           0.88     10634
   macro avg       0.81      0.81      0.81     10634
weighted avg       0.88      0.88      0.88     10634



In [66]:
########## score auf unsere trainingdaten

score_print(y_train,rfc.predict(X_train))

[[8031   73    0    0    0    0    0]
 [ 101 8005    9    0    0    0    0]
 [   2  386 7271  432   10    0    0]
 [   0   15  424 6744  907   12    1]
 [   0    1   42 1209 6634  349   19]
 [   0    0   18  357  446 6839  399]
 [   0    0   11   97   57  197 7973]]
              precision    recall  f1-score   support

           A       0.99      0.99      0.99      8104
           B       0.94      0.99      0.96      8115
           C       0.94      0.90      0.92      8101
           D       0.76      0.83      0.80      8103
           E       0.82      0.80      0.81      8254
           F       0.92      0.85      0.88      8059
           G       0.95      0.96      0.95      8335

    accuracy                           0.90     57071
   macro avg       0.90      0.90      0.90     57071
weighted avg       0.90      0.90      0.90     57071

