In [1]:
%store -r X_train X_test y_grade_train y_grade_test

y_train = y_grade_train
y_test = y_grade_test

In [2]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import svm

from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import LinearSVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, classification_report, roc_auc_score


In [3]:
##### Funktion to printe the scores
def score_print(y,y_pred):
    
    cm = confusion_matrix(y,y_pred)
    print(cm)
    cp= classification_report(y,y_pred)
    print(cp)
    #roc = roc_auc_score(y, y_pred)
    #print(roc)
    

In [4]:
###### Naiv-estimator

# TODO: Total number of records
n_records = len(y_train)

# TODO: Different grades
grades = pd.DataFrame(y_train.value_counts())

# TODO: Mmost frequent grade 
most_frequent_grade = grades[grades[0] == int(grades.max())].index.tolist()[0]

# TODO: Percentage of individuals whose income is more than $50,000
percent = float(100 * grades.max() / n_records)

# Print the results
print ("Total number of records: {}".format(n_records))
print ("Individuals have grades: {}".format(grades))
print ("Individuals have most likely grade: {}".format(most_frequent_grade))
print ("Individuals have most likely grade with percent: {:.2f}%".format(percent))

Total number of records: 114128
Individuals have grades:        0
A  16304
D  16304
C  16304
E  16304
F  16304
B  16304
G  16304
Individuals have most likely grade: A
Individuals have most likely grade with percent: 14.29%


In [5]:
####fit von log reg

lr = LogisticRegression(max_iter=10000, C = 2.0, random_state=70)
lr.fit(X_train, y_train)

y_grade_pred_lr_test = lr.predict(X_test)
score_print(y_test,y_grade_pred_lr_test)

[[2475   69    0    0    0    0    0]
 [  76 2821  179    0    0    0    0]
 [   1  104 1860  183    0    0    0]
 [   2    0  145 1165  143    0    0]
 [   1    0    0  117  584  107    0]
 [   0    0    0    0   45  223   34]
 [   0    0    0    0    0   26   83]]
              precision    recall  f1-score   support

           A       0.97      0.97      0.97      2544
           B       0.94      0.92      0.93      3076
           C       0.85      0.87      0.86      2148
           D       0.80      0.80      0.80      1455
           E       0.76      0.72      0.74       809
           F       0.63      0.74      0.68       302
           G       0.71      0.76      0.73       109

    accuracy                           0.88     10443
   macro avg       0.81      0.83      0.82     10443
weighted avg       0.88      0.88      0.88     10443



In [6]:
########## score auf unsere trainingdaten
y_grade_pred_lr_train = lr.predict(X_train)

score_print(y_train,y_grade_pred_lr_train)

[[16045   259     0     0     0     0     0]
 [  291 15262   751     0     0     0     0]
 [    3   527 14795   979     0     0     0]
 [    4     1   861 13933  1505     0     0]
 [    5     2     5  1499 13221  1572     0]
 [    0     0     0     0  1735 12880  1689]
 [    0     0     0     0     0  1571 14733]]
              precision    recall  f1-score   support

           A       0.98      0.98      0.98     16304
           B       0.95      0.94      0.94     16304
           C       0.90      0.91      0.90     16304
           D       0.85      0.85      0.85     16304
           E       0.80      0.81      0.81     16304
           F       0.80      0.79      0.80     16304
           G       0.90      0.90      0.90     16304

    accuracy                           0.88    114128
   macro avg       0.88      0.88      0.88    114128
weighted avg       0.88      0.88      0.88    114128



In [7]:
%store y_grade_pred_lr_train y_grade_pred_lr_test

Stored 'y_grade_pred_lr_train' (ndarray)
Stored 'y_grade_pred_lr_test' (ndarray)


In [8]:
######## DecisionTree

dtc = DecisionTreeClassifier(max_depth=10, min_samples_split=5, random_state=70)
dtc.fit(X_train,y_train)
y_grade_pred_dtc_test=dtc.predict(X_test)
score_print(y_test,y_grade_pred_dtc_test)

[[2544    0    0    0    0    0    0]
 [   1 3072    2    0    1    0    0]
 [   0    4 2101   43    0    0    0]
 [   0    1   10 1437    7    0    0]
 [   0    1    0   44  758    6    0]
 [   0    0    0    0   11  278   13]
 [   0    0    0    0    0    8  101]]
              precision    recall  f1-score   support

           A       1.00      1.00      1.00      2544
           B       1.00      1.00      1.00      3076
           C       0.99      0.98      0.99      2148
           D       0.94      0.99      0.96      1455
           E       0.98      0.94      0.96       809
           F       0.95      0.92      0.94       302
           G       0.89      0.93      0.91       109

    accuracy                           0.99     10443
   macro avg       0.96      0.96      0.96     10443
weighted avg       0.99      0.99      0.99     10443



In [9]:
########## score auf unsere trainingdaten
y_grade_pred_dtc_train = dtc.predict(X_train)
score_print(y_train,y_grade_pred_dtc_train)

[[16303     0     1     0     0     0     0]
 [    1 16268    34     1     0     0     0]
 [    0    76 15884   344     0     0     0]
 [    0     1   207 15644   452     0     0]
 [    0     2     5   702 15068   525     2]
 [    0     0     0     0   680 14923   701]
 [    0     0     0     0     0   534 15770]]
              precision    recall  f1-score   support

           A       1.00      1.00      1.00     16304
           B       1.00      1.00      1.00     16304
           C       0.98      0.97      0.98     16304
           D       0.94      0.96      0.95     16304
           E       0.93      0.92      0.93     16304
           F       0.93      0.92      0.92     16304
           G       0.96      0.97      0.96     16304

    accuracy                           0.96    114128
   macro avg       0.96      0.96      0.96    114128
weighted avg       0.96      0.96      0.96    114128



In [10]:
%store y_grade_pred_dtc_train y_grade_pred_dtc_test

Stored 'y_grade_pred_dtc_train' (ndarray)
Stored 'y_grade_pred_dtc_test' (ndarray)


In [11]:
##### RandomForestClassifier

rfc= RandomForestClassifier(max_depth=10,min_samples_split=7)
rfc.fit(X_train,y_train)
y_grade_pred_rfc_test=rfc.predict(X_test)
score_print(y_test,y_grade_pred_rfc_test)

[[2487   57    0    0    0    0    0]
 [  70 2967   39    0    0    0    0]
 [   1  178 1795  161   12    1    0]
 [   2    9  268  932  241    3    0]
 [   1    0   38  225  491   48    6]
 [   0    0    4   30   57  180   31]
 [   0    0    0    3    4   10   92]]
              precision    recall  f1-score   support

           A       0.97      0.98      0.97      2544
           B       0.92      0.96      0.94      3076
           C       0.84      0.84      0.84      2148
           D       0.69      0.64      0.66      1455
           E       0.61      0.61      0.61       809
           F       0.74      0.60      0.66       302
           G       0.71      0.84      0.77       109

    accuracy                           0.86     10443
   macro avg       0.78      0.78      0.78     10443
weighted avg       0.85      0.86      0.85     10443



In [12]:
########## score auf unsere trainingdaten
y_grade_pred_rfc_train =rfc.predict(X_train)
score_print(y_train,y_grade_pred_rfc_train)

[[16140   164     0     0     0     0     0]
 [  236 15975    93     0     0     0     0]
 [    3   873 14600   757    66     5     0]
 [    4    58  1483 12533  2216     8     2]
 [    4     3   365  2619 12727   576    10]
 [    0     0   182   846  1285 13214   777]
 [    0     0    98   256    28   296 15626]]
              precision    recall  f1-score   support

           A       0.98      0.99      0.99     16304
           B       0.94      0.98      0.96     16304
           C       0.87      0.90      0.88     16304
           D       0.74      0.77      0.75     16304
           E       0.78      0.78      0.78     16304
           F       0.94      0.81      0.87     16304
           G       0.95      0.96      0.96     16304

    accuracy                           0.88    114128
   macro avg       0.88      0.88      0.88    114128
weighted avg       0.88      0.88      0.88    114128



In [13]:
%store y_grade_pred_rfc_train y_grade_pred_rfc_test

Stored 'y_grade_pred_rfc_train' (ndarray)
Stored 'y_grade_pred_rfc_test' (ndarray)
