In [99]:
%store -r X_train X_test y_loan_status_train y_loan_status_test

In [100]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import svm

from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import LinearSVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, classification_report, roc_auc_score


In [101]:
##### Funktion to printe the scores
def score_print(y,y_pred):
    
    cm = confusion_matrix(y,y_pred)
    print(cm)
    cp= classification_report(y,y_pred)
    print(cp)
    roc = roc_auc_score(y, y_pred)
    print(roc)
    

In [102]:
###### Naiv-estimator

# TODO: Total number of records
n_records = len(y_train)

# TODO: People with Charged off
charged_off = sum(y_train == 1)

# TODO: Percentage of individuals with Charged Off
percent = float(100 * charged_off / n_records)

# Print the results
print ("Total number of records: {}".format(n_records))
print ("Individuals with Charged Off: {}".format(charged_off))
print ("Individuals percent of Charged Off: {:.2f}%".format(percent))

Total number of records: 55513
Individuals with Charged Off: 27832
Individuals percent of Charged Off: 50.14%


In [103]:
####fit von log reg

lr = LogisticRegression(max_iter=10000, C = 2.0, random_state=70)
lr.fit(X_train, y_train)
lr.score(X_train, y_train)
y_pred = lr.predict(X_test)
score_print(y_test,y_pred)

[[6157 2631]
 [1006  601]]
              precision    recall  f1-score   support

           0       0.86      0.70      0.77      8788
           1       0.19      0.37      0.25      1607

    accuracy                           0.65     10395
   macro avg       0.52      0.54      0.51     10395
weighted avg       0.76      0.65      0.69     10395

0.5373016366437346


In [104]:
########## score auf unsere trainingdaten

score_print(y_train,lr.predict(X_train))

[[17159 10522]
 [10656 17176]]
              precision    recall  f1-score   support

           0       0.62      0.62      0.62     27681
           1       0.62      0.62      0.62     27832

    accuracy                           0.62     55513
   macro avg       0.62      0.62      0.62     55513
weighted avg       0.62      0.62      0.62     55513

0.6185075171544111


In [105]:
%store -r y_grade_pred_lr_train y_grade_pred_lr_test

In [106]:
for grade in ["A", "B", "C", "D", "E", "F", "G"]:
#for grade in ["A", "B"]:
    mask_train = y_grade_pred_lr_train == grade
    mask_test = y_grade_pred_lr_test == grade

    X_train_masked, y_train_masked = X_train[mask_train], y_train[mask_train]
    X_test_masked, y_test_masked = X_test[mask_test], y_test[mask_test]

    lr.fit(X_train_masked, y_train_masked)
    lr.score(X_train_masked, y_train_masked)

    y_loan_status_pred_lr_test = lr.predict(X_test_masked)
    score_print(y_test_masked,y_loan_status_pred_lr_test)

ValueError: Item wrong length 114142 instead of 55513.

In [107]:
######## DecisionTree

dtc = DecisionTreeClassifier(max_depth=10, min_samples_split=5, random_state=70)
dtc.fit(X_train,y_train)
y_pred_dtc=dtc.predict(X_test)
score_print(y_test,y_pred_dtc)

[[5610 3178]
 [ 819  788]]
              precision    recall  f1-score   support

           0       0.87      0.64      0.74      8788
           1       0.20      0.49      0.28      1607

    accuracy                           0.62     10395
   macro avg       0.54      0.56      0.51     10395
weighted avg       0.77      0.62      0.67     10395

0.5643626017149029


In [108]:
########## score auf unsere trainingdaten
 
score_print(y_train,dtc.predict(X_train))

[[17303 10378]
 [ 6988 20844]]
              precision    recall  f1-score   support

           0       0.71      0.63      0.67     27681
           1       0.67      0.75      0.71     27832

    accuracy                           0.69     55513
   macro avg       0.69      0.69      0.69     55513
weighted avg       0.69      0.69      0.69     55513

0.6870039514881691


In [109]:
%store -r y_grade_pred_dtc_train y_grade_pred_dtc_test

In [110]:
for grade in ["A", "B", "C", "D", "E", "F", "G"]:
#for grade in ["A", "B"]:
    mask_train = y_grade_pred_lr_train == grade
    mask_test = y_grade_pred_lr_test == grade

    X_train_masked, y_train_masked = X_train[mask_train], y_train[mask_train]
    X_test_masked, y_test_masked = X_test[mask_test], y_test[mask_test]

    dtc.fit(X_train_masked, y_train_masked)

    y_loan_status_pred_dtc_test = dtc.predict(X_test_masked)
    score_print(y_test_masked,y_loan_status_pred_dtc_test)

ValueError: Item wrong length 114142 instead of 55513.

In [121]:
##### RandomForestClassifier

rfc= RandomForestClassifier(max_depth=10,min_samples_split=7)
rfc.fit(X_train,y_train)
y_pred_rfc=rfc.predict(X_test)
score_print(y_test,y_pred_rfc)

[[6513 2275]
 [ 912  695]]
              precision    recall  f1-score   support

           0       0.88      0.74      0.80      8788
           1       0.23      0.43      0.30      1607

    accuracy                           0.69     10395
   macro avg       0.56      0.59      0.55     10395
weighted avg       0.78      0.69      0.73     10395

0.5868035738613978


In [122]:
########## score auf unsere trainingdaten

score_print(y_train,rfc.predict(X_train))

[[19938  7743]
 [ 6706 21126]]
              precision    recall  f1-score   support

           0       0.75      0.72      0.73     27681
           1       0.73      0.76      0.75     27832

    accuracy                           0.74     55513
   macro avg       0.74      0.74      0.74     55513
weighted avg       0.74      0.74      0.74     55513

0.7396658862898862


In [123]:
%store -r y_grade_pred_rfc_train y_grade_pred_rfc_test

In [94]:
for grade in ["A", "B", "C", "D", "E", "F", "G"]:
#for grade in ["A", "B"]:
    mask_train = y_grade_pred_lr_train == grade
    mask_test = y_grade_pred_lr_test == grade

    X_train_masked, y_train_masked = X_train[mask_train], y_train[mask_train]
    X_test_masked, y_test_masked = X_test[mask_test], y_test[mask_test]

    rfc.fit(X_train_masked, y_train_masked)

    y_loan_status_pred_rfc_test = rfc.predict(X_test_masked)
    score_print(y_test_masked,y_loan_status_pred_rfc_test)

[[1942  447]
 [ 104   49]]
              precision    recall  f1-score   support

           0       0.95      0.81      0.88      2389
           1       0.10      0.32      0.15       153

    accuracy                           0.78      2542
   macro avg       0.52      0.57      0.51      2542
weighted avg       0.90      0.78      0.83      2542

0.5665769307583504
[[1908  741]
 [ 223  156]]
              precision    recall  f1-score   support

           0       0.90      0.72      0.80      2649
           1       0.17      0.41      0.24       379

    accuracy                           0.68      3028
   macro avg       0.53      0.57      0.52      3028
weighted avg       0.81      0.68      0.73      3028

0.5659406496801201
[[1400  417]
 [ 276  101]]
              precision    recall  f1-score   support

           0       0.84      0.77      0.80      1817
           1       0.19      0.27      0.23       377

    accuracy                           0.68      2194
   macro 