In [8]:
%store -r X_train X_test y_loan_status_train y_loan_status_test

y_train = y_loan_status_train
y_test = y_loan_status_test

In [9]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import svm

from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import LinearSVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, classification_report, roc_auc_score


In [10]:
##### Funktion to printe the scores
def score_print(y,y_pred):
    
    cm = confusion_matrix(y,y_pred)
    print(cm)
    cp= classification_report(y,y_pred)
    print(cp)
    roc = roc_auc_score(y, y_pred)
    print(roc)
    

In [11]:
###### Naiv-estimator

# TODO: Total number of records
n_records = len(y_train)

# TODO: People with Charged off
charged_off = sum(y_train == 1)

# TODO: Percentage of individuals with Charged Off
percent = float(100 * charged_off / n_records)

# Print the results
print ("Total number of records: {}".format(n_records))
print ("Individuals with Charged Off: {}".format(charged_off))
print ("Individuals percent of Charged Off: {:.2f}%".format(percent))

Total number of records: 114128
Individuals with Charged Off: 57064
Individuals percent of Charged Off: 50.00%


In [12]:
####fit von log reg

lr = LogisticRegression(max_iter=10000, C = 2.0, random_state=70)
lr.fit(X_train, y_train)
lr.score(X_train, y_train)
y_pred = lr.predict(X_test)
score_print(y_test,y_pred)

[[6164 2864]
 [ 813  602]]
              precision    recall  f1-score   support

           0       0.88      0.68      0.77      9028
           1       0.17      0.43      0.25      1415

    accuracy                           0.65     10443
   macro avg       0.53      0.55      0.51     10443
weighted avg       0.79      0.65      0.70     10443

0.554103214029067


In [13]:
########## score auf unsere trainingdaten

score_print(y_train,lr.predict(X_train))

[[37085 19979]
 [18522 38542]]
              precision    recall  f1-score   support

           0       0.67      0.65      0.66     57064
           1       0.66      0.68      0.67     57064

    accuracy                           0.66    114128
   macro avg       0.66      0.66      0.66    114128
weighted avg       0.66      0.66      0.66    114128

0.6626507079770083


In [14]:
%store -r y_grade_pred_lr_train y_grade_pred_lr_test

In [15]:
for grade in ["A", "B", "C", "D", "E", "F", "G"]:
#for grade in ["A", "B"]:
    mask_train = y_grade_pred_lr_train == grade
    mask_test = y_grade_pred_lr_test == grade

    X_train_masked, y_train_masked = X_train[mask_train], y_train[mask_train]
    X_test_masked, y_test_masked = X_test[mask_test], y_test[mask_test]

    lr.fit(X_train_masked, y_train_masked)
    lr.score(X_train_masked, y_train_masked)

    y_loan_status_pred_lr_test = lr.predict(X_test_masked)
    score_print(y_test_masked,y_loan_status_pred_lr_test)

[[1751  656]
 [  97   51]]
              precision    recall  f1-score   support

           0       0.95      0.73      0.82      2407
           1       0.07      0.34      0.12       148

    accuracy                           0.71      2555
   macro avg       0.51      0.54      0.47      2555
weighted avg       0.90      0.71      0.78      2555

0.536028082507102
[[1817  821]
 [ 199  157]]
              precision    recall  f1-score   support

           0       0.90      0.69      0.78      2638
           1       0.16      0.44      0.24       356

    accuracy                           0.66      2994
   macro avg       0.53      0.56      0.51      2994
weighted avg       0.81      0.66      0.72      2994

0.5648953071359815
[[1254  587]
 [ 193  150]]
              precision    recall  f1-score   support

           0       0.87      0.68      0.76      1841
           1       0.20      0.44      0.28       343

    accuracy                           0.64      2184
   macro a

In [16]:
######## DecisionTree

dtc = DecisionTreeClassifier(max_depth=10, min_samples_split=5, random_state=70)
dtc.fit(X_train,y_train)
y_pred_dtc=dtc.predict(X_test)
score_print(y_test,y_pred_dtc)

[[6556 2472]
 [ 860  555]]
              precision    recall  f1-score   support

           0       0.88      0.73      0.80      9028
           1       0.18      0.39      0.25      1415

    accuracy                           0.68     10443
   macro avg       0.53      0.56      0.52     10443
weighted avg       0.79      0.68      0.72     10443

0.5592056750024659


In [17]:
########## score auf unsere trainingdaten
 
score_print(y_train,dtc.predict(X_train))

[[39841 17223]
 [15065 41999]]
              precision    recall  f1-score   support

           0       0.73      0.70      0.71     57064
           1       0.71      0.74      0.72     57064

    accuracy                           0.72    114128
   macro avg       0.72      0.72      0.72    114128
weighted avg       0.72      0.72      0.72    114128

0.7170895836254031


In [18]:
%store -r y_grade_pred_dtc_train y_grade_pred_dtc_test

In [19]:
for grade in ["A", "B", "C", "D", "E", "F", "G"]:
#for grade in ["A", "B"]:
    mask_train = y_grade_pred_lr_train == grade
    mask_test = y_grade_pred_lr_test == grade

    X_train_masked, y_train_masked = X_train[mask_train], y_train[mask_train]
    X_test_masked, y_test_masked = X_test[mask_test], y_test[mask_test]

    dtc.fit(X_train_masked, y_train_masked)

    y_loan_status_pred_dtc_test = dtc.predict(X_test_masked)
    score_print(y_test_masked,y_loan_status_pred_dtc_test)

[[1909  498]
 [ 101   47]]
              precision    recall  f1-score   support

           0       0.95      0.79      0.86      2407
           1       0.09      0.32      0.14       148

    accuracy                           0.77      2555
   macro avg       0.52      0.56      0.50      2555
weighted avg       0.90      0.77      0.82      2555

0.5553355079217148
[[1659  979]
 [ 217  139]]
              precision    recall  f1-score   support

           0       0.88      0.63      0.74      2638
           1       0.12      0.39      0.19       356

    accuracy                           0.60      2994
   macro avg       0.50      0.51      0.46      2994
weighted avg       0.79      0.60      0.67      2994

0.5096674787675375
[[1042  799]
 [ 174  169]]
              precision    recall  f1-score   support

           0       0.86      0.57      0.68      1841
           1       0.17      0.49      0.26       343

    accuracy                           0.55      2184
   macro 

In [20]:
##### RandomForestClassifier

rfc= RandomForestClassifier(max_depth=10,min_samples_split=7)
rfc.fit(X_train,y_train)
y_pred_rfc=rfc.predict(X_test)
score_print(y_test,y_pred_rfc)

[[6834 2194]
 [ 850  565]]
              precision    recall  f1-score   support

           0       0.89      0.76      0.82      9028
           1       0.20      0.40      0.27      1415

    accuracy                           0.71     10443
   macro avg       0.55      0.58      0.54     10443
weighted avg       0.80      0.71      0.74     10443

0.5781357879921282


In [21]:
########## score auf unsere trainingdaten

score_print(y_train,rfc.predict(X_train))

[[41352 15712]
 [14190 42874]]
              precision    recall  f1-score   support

           0       0.74      0.72      0.73     57064
           1       0.73      0.75      0.74     57064

    accuracy                           0.74    114128
   macro avg       0.74      0.74      0.74    114128
weighted avg       0.74      0.74      0.74    114128

0.7379959343894575


In [22]:
%store -r y_grade_pred_rfc_train y_grade_pred_rfc_test

In [23]:
for grade in ["A", "B", "C", "D", "E", "F", "G"]:
#for grade in ["A", "B"]:
    mask_train = y_grade_pred_lr_train == grade
    mask_test = y_grade_pred_lr_test == grade

    X_train_masked, y_train_masked = X_train[mask_train], y_train[mask_train]
    X_test_masked, y_test_masked = X_test[mask_test], y_test[mask_test]

    rfc.fit(X_train_masked, y_train_masked)

    y_loan_status_pred_rfc_test = rfc.predict(X_test_masked)
    score_print(y_test_masked,y_loan_status_pred_rfc_test)

[[1952  455]
 [ 107   41]]
              precision    recall  f1-score   support

           0       0.95      0.81      0.87      2407
           1       0.08      0.28      0.13       148

    accuracy                           0.78      2555
   macro avg       0.52      0.54      0.50      2555
weighted avg       0.90      0.78      0.83      2555

0.5439975184989726
[[1860  778]
 [ 211  145]]
              precision    recall  f1-score   support

           0       0.90      0.71      0.79      2638
           1       0.16      0.41      0.23       356

    accuracy                           0.67      2994
   macro avg       0.53      0.56      0.51      2994
weighted avg       0.81      0.67      0.72      2994

0.5561914882742288
[[1491  350]
 [ 242  101]]
              precision    recall  f1-score   support

           0       0.86      0.81      0.83      1841
           1       0.22      0.29      0.25       343

    accuracy                           0.73      2184
   macro 