In [7]:
%store -r X_train X_test y_loan_status_train y_loan_status_test

y_train = y_loan_status_train
y_test = y_loan_status_test

In [8]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import svm

from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import LinearSVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, classification_report, roc_auc_score


In [9]:
##### Funktion to printe the scores
def score_print(y,y_pred):
    
    cm = confusion_matrix(y,y_pred)
    print(cm)
    cp= classification_report(y,y_pred)
    print(cp)
    roc = roc_auc_score(y, y_pred)
    print(roc)
    

In [10]:
###### Naiv-estimator

# TODO: Total number of records
n_records = len(y_train)

# TODO: People with Charged off
charged_off = sum(y_train == 1)

# TODO: Percentage of individuals with Charged Off
percent = float(100 * charged_off / n_records)

# Print the results
print ("Total number of records: {}".format(n_records))
print ("Individuals with Charged Off: {}".format(charged_off))
print ("Individuals percent of Charged Off: {:.2f}%".format(percent))

Total number of records: 108122
Individuals with Charged Off: 54061
Individuals percent of Charged Off: 50.00%


In [11]:
####fit von log reg

lr = LogisticRegression(max_iter=10000, C = 2.0, random_state=70)
lr.fit(X_train, y_train)
lr.score(X_train, y_train)
y_pred = lr.predict(X_test)
score_print(y_test,y_pred)

[[5785 2499]
 [ 881  527]]
              precision    recall  f1-score   support

           0       0.87      0.70      0.77      8284
           1       0.17      0.37      0.24      1408

    accuracy                           0.65      9692
   macro avg       0.52      0.54      0.51      9692
weighted avg       0.77      0.65      0.70      9692

0.5363119554124051


In [12]:
########## score auf unsere trainingdaten

score_print(y_train,lr.predict(X_train))

[[34896 19165]
 [19707 34354]]
              precision    recall  f1-score   support

           0       0.64      0.65      0.64     54061
           1       0.64      0.64      0.64     54061

    accuracy                           0.64    108122
   macro avg       0.64      0.64      0.64    108122
weighted avg       0.64      0.64      0.64    108122

0.6404801982945192


In [13]:
%store -r y_grade_pred_lr_train y_grade_pred_lr_test

In [14]:
for grade in ["A", "B", "C", "D", "E", "F", "G"]:
#for grade in ["A", "B"]:
    mask_train = y_grade_pred_lr_train == grade
    mask_test = y_grade_pred_lr_test == grade

    X_train_masked, y_train_masked = X_train[mask_train], y_train[mask_train]
    X_test_masked, y_test_masked = X_test[mask_test], y_test[mask_test]

    lr.fit(X_train_masked, y_train_masked)
    lr.score(X_train_masked, y_train_masked)

    y_loan_status_pred_lr_test = lr.predict(X_test_masked)
    score_print(y_test_masked,y_loan_status_pred_lr_test)

[[1837  578]
 [ 107   48]]
              precision    recall  f1-score   support

           0       0.94      0.76      0.84      2415
           1       0.08      0.31      0.12       155

    accuracy                           0.73      2570
   macro avg       0.51      0.54      0.48      2570
weighted avg       0.89      0.73      0.80      2570

0.5351699726173779
[[1700  758]
 [ 185  168]]
              precision    recall  f1-score   support

           0       0.90      0.69      0.78      2458
           1       0.18      0.48      0.26       353

    accuracy                           0.66      2811
   macro avg       0.54      0.58      0.52      2811
weighted avg       0.81      0.66      0.72      2811

0.5837699412452142
[[1107  504]
 [ 188  135]]
              precision    recall  f1-score   support

           0       0.85      0.69      0.76      1611
           1       0.21      0.42      0.28       323

    accuracy                           0.64      1934
   macro 

In [15]:
######## DecisionTree

dtc = DecisionTreeClassifier(max_depth=10, min_samples_split=5, random_state=70)
dtc.fit(X_train,y_train)
y_pred_dtc=dtc.predict(X_test)
score_print(y_test,y_pred_dtc)

[[5589 2695]
 [ 785  623]]
              precision    recall  f1-score   support

           0       0.88      0.67      0.76      8284
           1       0.19      0.44      0.26      1408

    accuracy                           0.64      9692
   macro avg       0.53      0.56      0.51      9692
weighted avg       0.78      0.64      0.69      9692

0.5585728307032176


In [16]:
########## score auf unsere trainingdaten
 
score_print(y_train,dtc.predict(X_train))

[[36504 17557]
 [13788 40273]]
              precision    recall  f1-score   support

           0       0.73      0.68      0.70     54061
           1       0.70      0.74      0.72     54061

    accuracy                           0.71    108122
   macro avg       0.71      0.71      0.71    108122
weighted avg       0.71      0.71      0.71    108122

0.7100960026636577


In [17]:
%store -r y_grade_pred_dtc_train y_grade_pred_dtc_test

In [18]:
for grade in ["A", "B", "C", "D", "E", "F", "G"]:
#for grade in ["A", "B"]:
    mask_train = y_grade_pred_lr_train == grade
    mask_test = y_grade_pred_lr_test == grade

    X_train_masked, y_train_masked = X_train[mask_train], y_train[mask_train]
    X_test_masked, y_test_masked = X_test[mask_test], y_test[mask_test]

    dtc.fit(X_train_masked, y_train_masked)

    y_loan_status_pred_dtc_test = dtc.predict(X_test_masked)
    score_print(y_test_masked,y_loan_status_pred_dtc_test)

[[1783  632]
 [ 103   52]]
              precision    recall  f1-score   support

           0       0.95      0.74      0.83      2415
           1       0.08      0.34      0.12       155

    accuracy                           0.71      2570
   macro avg       0.51      0.54      0.48      2570
weighted avg       0.89      0.71      0.79      2570

0.536893074200227
[[1672  786]
 [ 194  159]]
              precision    recall  f1-score   support

           0       0.90      0.68      0.77      2458
           1       0.17      0.45      0.24       353

    accuracy                           0.65      2811
   macro avg       0.53      0.57      0.51      2811
weighted avg       0.80      0.65      0.71      2811

0.5653263783402522
[[1209  402]
 [ 211  112]]
              precision    recall  f1-score   support

           0       0.85      0.75      0.80      1611
           1       0.22      0.35      0.27       323

    accuracy                           0.68      1934
   macro a

In [23]:
##### RandomForestClassifier

rfc= RandomForestClassifier(n_estimators=200, max_depth=10,min_samples_split=7)
rfc.fit(X_train,y_train)
y_pred_rfc=rfc.predict(X_test)
score_print(y_test,y_pred_rfc)

[[6251 2033]
 [ 838  570]]
              precision    recall  f1-score   support

           0       0.88      0.75      0.81      8284
           1       0.22      0.40      0.28      1408

    accuracy                           0.70      9692
   macro avg       0.55      0.58      0.55      9692
weighted avg       0.79      0.70      0.74      9692

0.579708350708924


In [20]:
########## score auf unsere trainingdaten

score_print(y_train,rfc.predict(X_train))

[[39505 14556]
 [13299 40762]]
              precision    recall  f1-score   support

           0       0.75      0.73      0.74     54061
           1       0.74      0.75      0.75     54061

    accuracy                           0.74    108122
   macro avg       0.74      0.74      0.74    108122
weighted avg       0.74      0.74      0.74    108122

0.7423743548953959


In [21]:
%store -r y_grade_pred_rfc_train y_grade_pred_rfc_test

In [22]:
for grade in ["A", "B", "C", "D", "E", "F", "G"]:
#for grade in ["A", "B"]:
    mask_train = y_grade_pred_lr_train == grade
    mask_test = y_grade_pred_lr_test == grade

    X_train_masked, y_train_masked = X_train[mask_train], y_train[mask_train]
    X_test_masked, y_test_masked = X_test[mask_test], y_test[mask_test]

    rfc.fit(X_train_masked, y_train_masked)

    y_loan_status_pred_rfc_test = rfc.predict(X_test_masked)
    score_print(y_test_masked,y_loan_status_pred_rfc_test)

[[1956  459]
 [ 118   37]]
              precision    recall  f1-score   support

           0       0.94      0.81      0.87      2415
           1       0.07      0.24      0.11       155

    accuracy                           0.78      2570
   macro avg       0.51      0.52      0.49      2570
weighted avg       0.89      0.78      0.83      2570

0.5243237828090563
[[1838  620]
 [ 216  137]]
              precision    recall  f1-score   support

           0       0.89      0.75      0.81      2458
           1       0.18      0.39      0.25       353

    accuracy                           0.70      2811
   macro avg       0.54      0.57      0.53      2811
weighted avg       0.81      0.70      0.74      2811

0.5679321957324986
[[1308  303]
 [ 223  100]]
              precision    recall  f1-score   support

           0       0.85      0.81      0.83      1611
           1       0.25      0.31      0.28       323

    accuracy                           0.73      1934
   macro 