In [31]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import svm
from sklearn.model_selection import GridSearchCV

%store -r X_train X_test y_test y_train score_print

from sklearn import svm



from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import LinearSVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, classification_report

no stored variable or alias score_print


In [2]:
def score_print(y,y_pred):
    
    cm = confusion_matrix(y,y_pred)
    print(cm)
    cp= classification_report(y,y_pred)
    print(cp)

In [4]:
##########GridSearchCV


In [7]:
# Defining parameter grid (as dictionary)
param_grid = {"n_neighbors" : range(5,15,2)
              
              
             }
knn=KNeighborsClassifier()
# Instantiate gridsearch and define the metric to optimize 
gs = GridSearchCV(knn,param_grid,
                  cv=5, verbose=5, n_jobs=-1)

gs.fit(X_train,y_train)


Fitting 5 folds for each of 5 candidates, totalling 25 fits


GridSearchCV(cv=5, estimator=KNeighborsClassifier(), n_jobs=-1,
             param_grid={'n_neighbors': range(5, 15, 2)}, verbose=5)

In [8]:
y_pred_gs=gs.predict(X_test)
score_print(y_test,y_pred_gs)
best_param=gs.best_params_

[[  522  3238]
 [  607 12647]]
              precision    recall  f1-score   support

           0       0.46      0.14      0.21      3760
           1       0.80      0.95      0.87     13254

    accuracy                           0.77     17014
   macro avg       0.63      0.55      0.54     17014
weighted avg       0.72      0.77      0.72     17014



In [9]:
best_param

{'n_neighbors': 9}

In [ ]:
#### log reg

In [18]:
# Defining parameter grid (as dictionary)
param_grid = {"max_iter" : [1000, 5000, 10000, 15000],
              "penalty": ["l1", "l2", "elasticnet"]
              
              
             }
lr=LogisticRegression()
# Instantiate gridsearch and define the metric to optimize 
gs = GridSearchCV(lr,param_grid,scoring="f1",
                  cv=5, verbose=5, n_jobs=-1)

gs.fit(X_train,y_train)

Fitting 5 folds for each of 12 candidates, totalling 60 fits


/Users/yusufcan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/sklearn/model_selection/_search.py:922: UserWarning: One or more of the test scores are non-finite: [       nan 0.87688252        nan        nan 0.87688252        nan
        nan 0.87688252        nan        nan 0.87688252        nan]
  warnings.warn(


GridSearchCV(cv=5, estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'max_iter': [1000, 5000, 10000, 15000],
                         'penalty': ['l1', 'l2', 'elasticnet']},
             scoring='f1', verbose=5)

In [19]:
y_pred_gs=gs.predict(X_test)
score_print(y_test,y_pred_gs)
best_param=gs.best_params_
best_param

[[  523  3237]
 [  384 12870]]
              precision    recall  f1-score   support

           0       0.58      0.14      0.22      3760
           1       0.80      0.97      0.88     13254

    accuracy                           0.79     17014
   macro avg       0.69      0.56      0.55     17014
weighted avg       0.75      0.79      0.73     17014



{'max_iter': 1000, 'penalty': 'l2'}

GridSearchCV(cv=5, estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'max_iter': [1000, 5000, 10000, 15000],
                         'penalty': ['l1', 'l2', 'elasticnet']},
             verbose=5)

In [22]:
######RandomForestClassifier
# Defining parameter grid (as dictionary)
param_grid = {"max_depth" : [1, 5, 10, 15, 20],
              "min_samples_split": [1,2,3,4,5,6,7,8,9,15,20],
              "criterion": ["gini", "entropy"]
              
              
             }
rfc=RandomForestClassifier()
# Instantiate gridsearch and define the metric to optimize 
gs = GridSearchCV(rfc,param_grid,scoring="f1",
                  cv=5, verbose=5, n_jobs=-1)

gs.fit(X_train,y_train)

Fitting 5 folds for each of 110 candidates, totalling 550 fits


/Users/yusufcan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/sklearn/model_selection/_search.py:922: UserWarning: One or more of the test scores are non-finite: [       nan 0.87580116 0.87580116 0.87580116 0.87580116 0.87580116
 0.87580116 0.87580116 0.87580116 0.87580116 0.87580116        nan
 0.87962155 0.87989678 0.87934422 0.87976672 0.87953412 0.87917414
 0.8796789  0.87972653 0.87968374 0.87976213        nan 0.88469426
 0.88471509 0.88508233 0.88478406 0.88500274 0.88478268 0.88496217
 0.88486876 0.88501262 0.88499876        nan 0.8848411  0.88515984
 0.88482277 0.88512077 0.88440076 0.88569232 0.88524201 0.88487713
 0.88550289 0.88540588        nan 0.88386416 0.88450702 0.88439856
 0.884888   0.88505366 0.88488256 0.88464057 0.88553269 0.88504388
 0.88472814        nan 0.87580116 0.87580116 0.87580116 0.87580116
 0.87580116 0.87580116 0.87580116 0.87580116 0.87580116 0.87580116
        nan 0.87906304 0.87925541 0.87989017 0.87928101 0.87872734
 0.87998454 0.87981539 0.87925

GridSearchCV(cv=5, estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [1, 5, 10, 15, 20],
                         'min_samples_split': [1, 2, 3, 4, 5, 6, 7, 8, 9, 15,
                                               20]},
             scoring='f1', verbose=5)

In [23]:
y_pred_gs=gs.predict(X_test)
score_print(y_test,y_pred_gs)
best_param=gs.best_params_
best_param

[[  565  3195]
 [  178 13076]]
              precision    recall  f1-score   support

           0       0.76      0.15      0.25      3760
           1       0.80      0.99      0.89     13254

    accuracy                           0.80     17014
   macro avg       0.78      0.57      0.57     17014
weighted avg       0.79      0.80      0.75     17014



{'criterion': 'gini', 'max_depth': 15, 'min_samples_split': 7}

In [ ]:
###DecisionTreeClassifier

In [27]:
# Defining parameter grid (as dictionary)
param_grid = {"max_depth" : [1, 5, 10, 15, 20, 25],
              "min_samples_split": [1,2,3,4,5,10,15],
              "min_samples_leaf": [1,2,3,4,5,10,15],
              "criterion": ["gini", "entropy"]
              
              
             }
dtc=DecisionTreeClassifier()
# Instantiate gridsearch and define the metric to optimize 
gs = GridSearchCV(dtc,param_grid,scoring="f1",
                  cv=5, verbose=5, n_jobs=-1)

gs.fit(X_train,y_train)

Fitting 5 folds for each of 588 candidates, totalling 2940 fits


/Users/yusufcan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/sklearn/model_selection/_search.py:922: UserWarning: One or more of the test scores are non-finite: [       nan 0.87580116 0.87580116 0.87580116 0.87580116 0.87580116
 0.87580116        nan 0.87580116 0.87580116 0.87580116 0.87580116
 0.87580116 0.87580116        nan 0.87580116 0.87580116 0.87580116
 0.87580116 0.87580116 0.87580116        nan 0.87580116 0.87580116
 0.87580116 0.87580116 0.87580116 0.87580116        nan 0.87580116
 0.87580116 0.87580116 0.87580116 0.87580116 0.87580116        nan
 0.87580116 0.87580116 0.87580116 0.87580116 0.87580116 0.87580116
        nan 0.87580116 0.87580116 0.87580116 0.87580116 0.87580116
 0.87580116        nan 0.88160581 0.88158558 0.88158007 0.88155984
 0.88160581 0.88160581        nan 0.88155984 0.88158007 0.88155984
 0.88155984 0.88160581 0.88155984        nan 0.88155444 0.88155444
 0.88153421 0.88158017 0.88153421 0.88155994        nan 0.88151396
 0.88151396 0.88151396 0.88149

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [1, 5, 10, 15, 20, 25],
                         'min_samples_leaf': [1, 2, 3, 4, 5, 10, 15],
                         'min_samples_split': [1, 2, 3, 4, 5, 10, 15]},
             scoring='f1', verbose=5)

In [28]:
y_pred_gs=gs.predict(X_test)
score_print(y_test,y_pred_gs)
best_param=gs.best_params_
best_param

[[  731  3029]
 [  422 12832]]
              precision    recall  f1-score   support

           0       0.63      0.19      0.30      3760
           1       0.81      0.97      0.88     13254

    accuracy                           0.80     17014
   macro avg       0.72      0.58      0.59     17014
weighted avg       0.77      0.80      0.75     17014



{'criterion': 'entropy',
 'max_depth': 5,
 'min_samples_leaf': 1,
 'min_samples_split': 4}

In [ ]:
###LinearSVC

In [40]:
# Defining parameter grid (as dictionary)
param_grid = {"loss" : ["hinge", "log", "squared_hinge", "modified_huber"],
              "max_iter": [10,20,30, 50, 60,100,],
              "penalty": ["l1", "l2", "elasticnet"]
              
              
             }
svc=LinearSVC()
# Instantiate gridsearch and define the metric to optimize 
gs = GridSearchCV(svc,param_grid,scoring="f1",
                  cv=5, verbose=5, n_jobs=-1)

gs.fit(X_train,y_train)

Fitting 5 folds for each of 72 candidates, totalling 360 fits


/Users/yusufcan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/sklearn/model_selection/_search.py:922: UserWarning: One or more of the test scores are non-finite: [       nan 0.87590599        nan        nan 0.87577092        nan
        nan 0.87577092        nan        nan 0.87577092        nan
        nan 0.87577092        nan        nan 0.87577092        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan 0.86878261        nan        nan 0.87858419        nan
        nan 0.87655446        nan        nan 0.87832172        nan
        nan 0.87827385        nan        nan 0.87840404        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan]
  warnings.warn(
/Users/yusuf

GridSearchCV(cv=5, estimator=LinearSVC(), n_jobs=-1,
             param_grid={'loss': ['hinge', 'log', 'squared_hinge',
                                  'modified_huber'],
                         'max_iter': [10, 20, 30, 50, 60, 100],
                         'penalty': ['l1', 'l2', 'elasticnet']},
             scoring='f1', verbose=5)

In [41]:
y_pred_gs=gs.predict(X_test)
score_print(y_test,y_pred_gs)
best_param=gs.best_params_
best_param

[[  103  3657]
 [   19 13235]]
              precision    recall  f1-score   support

           0       0.84      0.03      0.05      3760
           1       0.78      1.00      0.88     13254

    accuracy                           0.78     17014
   macro avg       0.81      0.51      0.47     17014
weighted avg       0.80      0.78      0.70     17014



{'loss': 'squared_hinge', 'max_iter': 20, 'penalty': 'l2'}

In [ ]:
######svm


In [43]:
# Defining parameter grid (as dictionary)
param_grid = {
              "kernel": ["rbf", "linear", "poly","sigmoid"],
                "decision_function_shape" : ['ovo', 'ovr']
              
              
             }
clf = svm.SVC()
# Instantiate gridsearch and define the metric to optimize 
gs = GridSearchCV(clf,param_grid,scoring="f1",
                  cv=5, verbose=5, n_jobs=-1)

gs.fit(X_train,y_train)

Fitting 5 folds for each of 8 candidates, totalling 40 fits


GridSearchCV(cv=5, estimator=SVC(), n_jobs=-1,
             param_grid={'decision_function_shape': ['ovo', 'ovr'],
                         'kernel': ['rbf', 'linear', 'poly', 'sigmoid']},
             scoring='f1', verbose=5)

In [44]:
y_pred_gs=gs.predict(X_test)
score_print(y_test,y_pred_gs)
best_param=gs.best_params_
best_param

[[  142  3618]
 [   24 13230]]
              precision    recall  f1-score   support

           0       0.86      0.04      0.07      3760
           1       0.79      1.00      0.88     13254

    accuracy                           0.79     17014
   macro avg       0.82      0.52      0.48     17014
weighted avg       0.80      0.79      0.70     17014



{'decision_function_shape': 'ovo', 'kernel': 'rbf'}

In [ ]:
#### info fpr den näachetn tag: unser y spinnt: 0 und 1 für die ereignisse tauschen und sehen was passiert
#### 2. featureselektion >> bessere untersuchung wäre anfällig
#### 3. 