In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import svm
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV

%store -r X_train X_test y_test y_train score_print

from sklearn import svm



from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import LinearSVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, classification_report

no stored variable or alias score_print


In [2]:
def score_print(y,y_pred):
    
    cm = confusion_matrix(y,y_pred)
    print(cm)
    cp= classification_report(y,y_pred)
    print(cp)

In [4]:
##########GridSearchCV


In [ ]:
# Defining parameter grid (as dictionary)
param_grid = {"n_neighbors" : range(5,15,2)
              
              
             }
knn=KNeighborsClassifier()
# Instantiate gridsearch and define the metric to optimize 
gs = GridSearchCV(knn,param_grid,
                  cv=5, verbose=5, n_jobs=-1)

gs.fit(X_train,y_train)


Fitting 5 folds for each of 5 candidates, totalling 25 fits


In [ ]:
y_pred_gs=gs.predict(X_test)
score_print(y_test,y_pred_gs)
best_param=gs.best_params_

In [ ]:
best_param

In [ ]:
#### log reg

In [26]:
# Defining parameter grid (as dictionary)
param_grid = {"max_iter" : [500, 1000,1500 ,2000,3000],
              "penalty": ["l1", "l2", "elasticnet"],
              "solver":['lbfgs',"liblinear"],
              "C": [1,2,3,4,5,10,15]
              
              
             }
lr=LogisticRegression()
# Instantiate gridsearch and define the metric to optimize 
gs = GridSearchCV(lr,param_grid,scoring="f1",
                  cv=5, verbose=5, n_jobs=-1)

gs.fit(X_train,y_train)

Fitting 5 folds for each of 210 candidates, totalling 1050 fits


/Users/yusufcan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/sklearn/model_selection/_search.py:922: UserWarning: One or more of the test scores are non-finite: [nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan na

ValueError: Solver lbfgs supports only 'l2' or 'none' penalties, got l1 penalty.

In [19]:
y_pred_gs=gs.predict(X_test)
score_print(y_test,y_pred_gs)
best_param=gs.best_params_
best_param

[[  523  3237]
 [  384 12870]]
              precision    recall  f1-score   support

           0       0.58      0.14      0.22      3760
           1       0.80      0.97      0.88     13254

    accuracy                           0.79     17014
   macro avg       0.69      0.56      0.55     17014
weighted avg       0.75      0.79      0.73     17014



{'max_iter': 1000, 'penalty': 'l2'}

GridSearchCV(cv=5, estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'max_iter': [1000, 5000, 10000, 15000],
                         'penalty': ['l1', 'l2', 'elasticnet']},
             verbose=5)

In [31]:
######RandomForestClassifier
# Defining parameter grid (as dictionary)
param_grid = {"max_depth" : [1, 5, 10, 15, 20],
              "min_samples_split": [5,6,7,8,9],
              "criterion": ["gini", "entropy"]
              
              
             }
rfc=RandomForestClassifier()
# Instantiate gridsearch and define the metric to optimize 
gs = GridSearchCV(rfc,param_grid,scoring="f1",
                  cv=5, verbose=5, n_jobs=-1)

gs.fit(X_train,y_train)

Fitting 5 folds for each of 50 candidates, totalling 250 fits


/Users/yusufcan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/sklearn/model_selection/_search.py:922: UserWarning: One or more of the test scores are non-finite: [nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan]
  warnings.warn(


GridSearchCV(cv=5, estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [1, 5, 10, 15, 20],
                         'min_samples_split': [5, 6, 7, 8, 9]},
             scoring='f1', verbose=5)

In [32]:
y_pred_gs=gs.predict(X_test)
score_print(y_test,y_pred_gs)
best_param=gs.best_params_
best_param

[[2490   42    4    0    0    0    9]
 [ 111 1590  249    0  260  249  639]
 [   2 1087  228    0  218  250  401]
 [   3  574  181    0  248  220  278]
 [   2  140  153    0  180  262  112]
 [   1   27   35    0   70  139   53]
 [   3   13    6    0   15   54   36]]
              precision    recall  f1-score   support

           A       0.95      0.98      0.97      2545
           B       0.46      0.51      0.48      3098
           C       0.27      0.10      0.15      2186
           D       0.00      0.00      0.00      1504
           E       0.18      0.21      0.20       849
           F       0.12      0.43      0.19       325
           G       0.02      0.28      0.04       127

    accuracy                           0.44     10634
   macro avg       0.29      0.36      0.29     10634
weighted avg       0.43      0.44      0.42     10634



/Users/yusufcan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/yusufcan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/yusufcan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start,

{'criterion': 'gini', 'max_depth': 1, 'min_samples_split': 5}

In [ ]:
###DecisionTreeClassifier

In [34]:
# Defining parameter grid (as dictionary)
param_grid = {"max_depth" : [1, 5, 10, 15, 20, 25],
              "min_samples_split": [1,2,3,4,5,10,15],
              "min_samples_leaf": [1,2,3,4,5,10,15],
              "criterion": ["gini", "entropy"]
              
              
             }
dtc=DecisionTreeClassifier()
# Instantiate gridsearch and define the metric to optimize 
gs = GridSearchCV(dtc,param_grid,scoring="f1",
                  cv=5, verbose=5, n_jobs=-1)

gs.fit(X_train,y_train)

Fitting 5 folds for each of 588 candidates, totalling 2940 fits


/Users/yusufcan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/sklearn/model_selection/_search.py:922: UserWarning: One or more of the test scores are non-finite: [nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan na

ValueError: min_samples_split must be an integer greater than 1 or a float in (0.0, 1.0]; got the integer 1

In [28]:
y_pred_gs=gs.predict(X_test)
score_print(y_test,y_pred_gs)
best_param=gs.best_params_
best_param

[[  731  3029]
 [  422 12832]]
              precision    recall  f1-score   support

           0       0.63      0.19      0.30      3760
           1       0.81      0.97      0.88     13254

    accuracy                           0.80     17014
   macro avg       0.72      0.58      0.59     17014
weighted avg       0.77      0.80      0.75     17014



{'criterion': 'entropy',
 'max_depth': 5,
 'min_samples_leaf': 1,
 'min_samples_split': 4}

In [ ]:
###LinearSVC

In [40]:
# Defining parameter grid (as dictionary)
param_grid = {"loss" : ["hinge", "log", "squared_hinge", "modified_huber"],
              "max_iter": [10,20,30, 50, 60,100,],
              "penalty": ["l1", "l2", "elasticnet"]
              
              
             }
svc=LinearSVC()
# Instantiate gridsearch and define the metric to optimize 
gs = GridSearchCV(svc,param_grid,scoring="f1",
                  cv=5, verbose=5, n_jobs=-1)

gs.fit(X_train,y_train)

Fitting 5 folds for each of 72 candidates, totalling 360 fits


/Users/yusufcan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/sklearn/model_selection/_search.py:922: UserWarning: One or more of the test scores are non-finite: [       nan 0.87590599        nan        nan 0.87577092        nan
        nan 0.87577092        nan        nan 0.87577092        nan
        nan 0.87577092        nan        nan 0.87577092        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan 0.86878261        nan        nan 0.87858419        nan
        nan 0.87655446        nan        nan 0.87832172        nan
        nan 0.87827385        nan        nan 0.87840404        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan]
  warnings.warn(
/Users/yusuf

GridSearchCV(cv=5, estimator=LinearSVC(), n_jobs=-1,
             param_grid={'loss': ['hinge', 'log', 'squared_hinge',
                                  'modified_huber'],
                         'max_iter': [10, 20, 30, 50, 60, 100],
                         'penalty': ['l1', 'l2', 'elasticnet']},
             scoring='f1', verbose=5)

In [41]:
y_pred_gs=gs.predict(X_test)
score_print(y_test,y_pred_gs)
best_param=gs.best_params_
best_param

[[  103  3657]
 [   19 13235]]
              precision    recall  f1-score   support

           0       0.84      0.03      0.05      3760
           1       0.78      1.00      0.88     13254

    accuracy                           0.78     17014
   macro avg       0.81      0.51      0.47     17014
weighted avg       0.80      0.78      0.70     17014



{'loss': 'squared_hinge', 'max_iter': 20, 'penalty': 'l2'}

In [ ]:
######svm


In [5]:
# Defining parameter grid (as dictionary)
param_grid = {
              "kernel": ["rbf", "linear", "poly","sigmoid"],
                "decision_function_shape" : ['ovo', 'ovr']
              
              
             }
clf = svm.SVC()
# Instantiate gridsearch and define the metric to optimize 
gs = GridSearchCV(clf,param_grid,scoring="f1",
                  cv=5, verbose=5, n_jobs=-1)

gs.fit(X_train,y_train)

Fitting 5 folds for each of 8 candidates, totalling 40 fits


/Users/yusufcan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/sklearn/model_selection/_search.py:922: UserWarning: One or more of the test scores are non-finite: [nan nan nan nan nan nan nan nan]
  warnings.warn(


GridSearchCV(cv=5, estimator=SVC(), n_jobs=-1,
             param_grid={'decision_function_shape': ['ovo', 'ovr'],
                         'kernel': ['rbf', 'linear', 'poly', 'sigmoid']},
             scoring='f1', verbose=5)

In [6]:
y_pred_gs=gs.predict(X_test)
score_print(y_test,y_pred_gs)
best_param=gs.best_params_
best_param

[[2458   87    0    0    0    0    0]
 [  66 2803  229    0    0    0    0]
 [   1  118 1854  213    0    0    0]
 [   2    0  143 1202  156    1    0]
 [   1    0    0  142  636   70    0]
 [   0    0    0    0   70  226   29]
 [   0    0    0    0    1   35   91]]
              precision    recall  f1-score   support

           A       0.97      0.97      0.97      2545
           B       0.93      0.90      0.92      3098
           C       0.83      0.85      0.84      2186
           D       0.77      0.80      0.79      1504
           E       0.74      0.75      0.74       849
           F       0.68      0.70      0.69       325
           G       0.76      0.72      0.74       127

    accuracy                           0.87     10634
   macro avg       0.81      0.81      0.81     10634
weighted avg       0.87      0.87      0.87     10634



{'decision_function_shape': 'ovo', 'kernel': 'rbf'}

In [ ]:
#### info fpr den näachetn tag: unser y spinnt: 0 und 1 für die ereignisse tauschen und sehen was passiert
#### 2. featureselektion >> bessere untersuchung wäre anfällig
#### 3. 

In [ ]:
#RandomSearchCV

In [ ]:
#KNN

In [3]:
# Defining parameter grid (as dictionary)
param_grid = {"n_neighbors" : [2,4,6,8,10,12,14]
              
              
             }
knn=KNeighborsClassifier()
# Instantiate randomsearch and define the metric to optimize 
rs = RandomizedSearchCV(knn, param_grid, scoring='f1',
                  cv=5, verbose=5, n_jobs=-1, n_iter=5)

rs.fit(X_train,y_train)

Fitting 5 folds for each of 5 candidates, totalling 25 fits


RandomizedSearchCV(cv=5, estimator=KNeighborsClassifier(), n_iter=5, n_jobs=-1,
                   param_distributions={'n_neighbors': [2, 4, 6, 8, 10, 12,
                                                        14]},
                   scoring='f1', verbose=5)

In [6]:
y_pred_rs=rs.predict(X_test)
score_print(y_test,y_pred_rs)
best_param=rs.best_params_
best_param

[[  514  3246]
 [  604 12650]]
              precision    recall  f1-score   support

           0       0.46      0.14      0.21      3760
           1       0.80      0.95      0.87     13254

    accuracy                           0.77     17014
   macro avg       0.63      0.55      0.54     17014
weighted avg       0.72      0.77      0.72     17014



{'n_neighbors': 14}

In [ ]:
### log reg

In [23]:
# Defining parameter grid (as dictionary)
param_grid = {"max_iter" : [1000, 5000, 10000, 15000],
              "penalty": ["l1", "l2", "elasticnet"],
              "C": [1,2,3,4,5,10,15],
              "solver":['lbfgs',"liblinear"]

             }
lr=LogisticRegression()
rs = RandomizedSearchCV(lr, param_grid, scoring='f1',
                  cv=5, verbose=5, n_jobs=-1, n_iter=5)

rs.fit(X_train,y_train)

Fitting 5 folds for each of 5 candidates, totalling 25 fits


/Users/yusufcan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/sklearn/model_selection/_search.py:922: UserWarning: One or more of the test scores are non-finite: [nan nan nan nan nan]
  warnings.warn(


RandomizedSearchCV(cv=5, estimator=LogisticRegression(), n_iter=5, n_jobs=-1,
                   param_distributions={'C': [1, 2, 3, 4, 5, 10, 15],
                                        'max_iter': [1000, 5000, 10000, 15000],
                                        'penalty': ['l1', 'l2', 'elasticnet'],
                                        'solver': ['lbfgs', 'liblinear']},
                   scoring='f1', verbose=5)

In [24]:
y_pred_rs=rs.predict(X_test)
score_print(y_test,y_pred_rs)
best_param=rs.best_params_
best_param

[[2470   75    0    0    0    0    0]
 [  68 2837  193    0    0    0    0]
 [   1  117 1860  208    0    0    0]
 [   2    0  145 1181  176    0    0]
 [   1    0    0  118  625  105    0]
 [   0    0    0    0   45  243   37]
 [   0    0    0    0    0   22  105]]
              precision    recall  f1-score   support

           A       0.97      0.97      0.97      2545
           B       0.94      0.92      0.93      3098
           C       0.85      0.85      0.85      2186
           D       0.78      0.79      0.78      1504
           E       0.74      0.74      0.74       849
           F       0.66      0.75      0.70       325
           G       0.74      0.83      0.78       127

    accuracy                           0.88     10634
   macro avg       0.81      0.83      0.82     10634
weighted avg       0.88      0.88      0.88     10634



{'solver': 'lbfgs', 'penalty': 'l2', 'max_iter': 1000, 'C': 2}

In [ ]:
######RandomForestClassifier

In [27]:
# Defining parameter grid (as dictionary)
param_grid = {"max_depth" : [1, 5, 10, 15, 20,25,30,35],
              "min_samples_split": [1,2,3,4,5,6,7,8,9,15,20],
              "criterion": ["gini", "entropy"]
              
              
             }
rfc=RandomForestClassifier()
# Instantiate randomsearch and define the metric to optimize 
rs = RandomizedSearchCV(rfc, param_grid, scoring='f1',
                  cv=5, verbose=5, n_jobs=-1, n_iter=5)

rs.fit(X_train,y_train)

Fitting 5 folds for each of 5 candidates, totalling 25 fits


/Users/yusufcan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/sklearn/model_selection/_search.py:922: UserWarning: One or more of the test scores are non-finite: [nan nan nan nan nan]
  warnings.warn(


RandomizedSearchCV(cv=5, estimator=RandomForestClassifier(), n_iter=5,
                   n_jobs=-1,
                   param_distributions={'criterion': ['gini', 'entropy'],
                                        'max_depth': [1, 5, 10, 15, 20, 25, 30,
                                                      35],
                                        'min_samples_split': [1, 2, 3, 4, 5, 6,
                                                              7, 8, 9, 15,
                                                              20]},
                   scoring='f1', verbose=5)

In [28]:
y_pred_rs=rs.predict(X_test)
score_print(y_test,y_pred_rs)
best_param=rs.best_params_
best_param

[[2293  188    0    0    0    3   61]
 [2217  538    0    0    0  196  147]
 [1429  136  167    5   41  229  179]
 [ 629   11    0   42  299  238  285]
 [ 191    0    0    9  252  269  128]
 [  33    0    0    6   86  140   60]
 [  15    0    0    1   18   54   39]]
              precision    recall  f1-score   support

           A       0.34      0.90      0.49      2545
           B       0.62      0.17      0.27      3098
           C       1.00      0.08      0.14      2186
           D       0.67      0.03      0.05      1504
           E       0.36      0.30      0.33       849
           F       0.12      0.43      0.19       325
           G       0.04      0.31      0.08       127

    accuracy                           0.33     10634
   macro avg       0.45      0.32      0.22     10634
weighted avg       0.59      0.33      0.27     10634



{'min_samples_split': 15, 'max_depth': 1, 'criterion': 'entropy'}

In [ ]:
###DecisionTreeClassifier

In [11]:
# Defining parameter grid (as dictionary)
param_grid = {"max_depth" : [1, 5, 10, 15, 20, 25],
              "min_samples_split": [1,2,3,4,5,10,15],
              "min_samples_leaf": [1,2,3,4,5,10,15],
              "criterion": ["gini", "entropy"]
              
              
             }
dtc=DecisionTreeClassifier()
# Instantiate randomsearch and define the metric to optimize 
rs = RandomizedSearchCV(dtc, param_grid, scoring='f1',
                  cv=5, verbose=5, n_jobs=-1, n_iter=5)

rs.fit(X_train,y_train)

Fitting 5 folds for each of 5 candidates, totalling 25 fits


RandomizedSearchCV(cv=5, estimator=DecisionTreeClassifier(), n_iter=5,
                   n_jobs=-1,
                   param_distributions={'criterion': ['gini', 'entropy'],
                                        'max_depth': [1, 5, 10, 15, 20, 25],
                                        'min_samples_leaf': [1, 2, 3, 4, 5, 10,
                                                             15],
                                        'min_samples_split': [1, 2, 3, 4, 5, 10,
                                                              15]},
                   scoring='f1', verbose=5)

In [12]:
y_pred_rs=rs.predict(X_test)
score_print(y_test,y_pred_rs)
best_param=rs.best_params_
best_param

[[  749  3011]
 [  401 12853]]
              precision    recall  f1-score   support

           0       0.65      0.20      0.31      3760
           1       0.81      0.97      0.88     13254

    accuracy                           0.80     17014
   macro avg       0.73      0.58      0.59     17014
weighted avg       0.78      0.80      0.76     17014



{'min_samples_split': 2,
 'min_samples_leaf': 3,
 'max_depth': 5,
 'criterion': 'gini'}

In [ ]:
###LinearSVC

In [17]:
# Defining parameter grid (as dictionary)
param_grid = {"loss" : ["hinge", "log", "squared_hinge", "modified_huber"],
              "max_iter": [10,20,30, 50, 60,100,],
              "penalty": ["l1", "l2", "elasticnet"]
              
              
             }
svc=LinearSVC()
# Instantiate randomsearch and define the metric to optimize 
rs = RandomizedSearchCV(svc, param_grid, scoring='f1',
                  cv=5, verbose=5, n_jobs=-1, n_iter=5)

rs.fit(X_train,y_train)

Fitting 5 folds for each of 5 candidates, totalling 25 fits


/Users/yusufcan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/sklearn/model_selection/_search.py:922: UserWarning: One or more of the test scores are non-finite: [0.87577092        nan        nan        nan        nan]
  warnings.warn(
/Users/yusufcan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/sklearn/svm/_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "


RandomizedSearchCV(cv=5, estimator=LinearSVC(), n_iter=5, n_jobs=-1,
                   param_distributions={'loss': ['hinge', 'log',
                                                 'squared_hinge'],
                                        'max_iter': [10, 20, 30, 50, 60, 100],
                                        'penalty': ['l1', 'l2']},
                   scoring='f1', verbose=5)

In [19]:
y_pred_rs=rs.predict(X_test)
score_print(y_test,y_pred_rs)
best_param=rs.best_params_
best_param

[[    0  3760]
 [    0 13254]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00      3760
           1       0.78      1.00      0.88     13254

    accuracy                           0.78     17014
   macro avg       0.39      0.50      0.44     17014
weighted avg       0.61      0.78      0.68     17014



/Users/yusufcan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/yusufcan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/yusufcan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start,

{'penalty': 'l2', 'max_iter': 20, 'loss': 'hinge'}

In [ ]:
######svm

In [3]:
param_grid = {
              "kernel": ["rbf", "linear", "poly","sigmoid"],
                "decision_function_shape" : ['ovo', 'ovr']
              
              
             }
clf = svm.SVC()
# Instantiate randomsearch and define the metric to optimize 
rs = RandomizedSearchCV(clf, param_grid, scoring='f1',
                  cv=5, verbose=5, n_jobs=-1, n_iter=5)

rs.fit(X_train,y_train)

Fitting 5 folds for each of 5 candidates, totalling 25 fits


/Users/yusufcan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/sklearn/model_selection/_search.py:922: UserWarning: One or more of the test scores are non-finite: [nan nan nan nan nan]
  warnings.warn(


RandomizedSearchCV(cv=5, estimator=SVC(), n_iter=5, n_jobs=-1,
                   param_distributions={'decision_function_shape': ['ovo',
                                                                    'ovr'],
                                        'kernel': ['rbf', 'linear', 'poly',
                                                   'sigmoid']},
                   scoring='f1', verbose=5)

In [4]:
y_pred_rs=rs.predict(X_test)
score_print(y_test,y_pred_rs)
best_param=rs.best_params_
best_param

[[2458   87    0    0    0    0    0]
 [  66 2803  229    0    0    0    0]
 [   1  118 1854  213    0    0    0]
 [   2    0  143 1202  156    1    0]
 [   1    0    0  142  636   70    0]
 [   0    0    0    0   70  226   29]
 [   0    0    0    0    1   35   91]]
              precision    recall  f1-score   support

           A       0.97      0.97      0.97      2545
           B       0.93      0.90      0.92      3098
           C       0.83      0.85      0.84      2186
           D       0.77      0.80      0.79      1504
           E       0.74      0.75      0.74       849
           F       0.68      0.70      0.69       325
           G       0.76      0.72      0.74       127

    accuracy                           0.87     10634
   macro avg       0.81      0.81      0.81     10634
weighted avg       0.87      0.87      0.87     10634



{'kernel': 'rbf', 'decision_function_shape': 'ovo'}