In [5]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import svm



from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import LinearSVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, classification_report

%store -r X y
X["grade_B"]

0        1
1        0
2        0
3        0
4        1
        ..
72221    0
72222    0
72223    0
72224    0
72225    0
Name: grade_B, Length: 72226, dtype: uint8

In [6]:
##### Funktion scor


def score_print(y,y_pred):
    
    cm = confusion_matrix(y,y_pred)
    print(cm)
    cp= classification_report(y,y_pred)
    print(cp)
    

In [7]:
###### Naiv-estimator


# TODO: Total number of records
n_records = len(X)

# TODO: Number of records where individual's income is more than $50,000
fully_paid = sum(y==10)

# TODO: Number of records where individual's income is at most $50,000
charged_off = n_records - fully_paid

# TODO: Percentage of individuals whose income is more than $50,000
greater_percent = 100 * fully_paid / n_records

# Print the results
print ("Total number of records: {}".format(n_records))
print ("Individuals has paid her credit fully: {}".format(fully_paid))
print ("Individuals hasn't paid her credit: {}".format(charged_off))
print ("Percentage of individuals that paid ther credit: {:.2f}%".format(greater_percent))

Total number of records: 72226
Individuals has paid her credit fully: 0
Individuals hasn't paid her credit: 72226
Percentage of individuals that paid ther credit: 0.00%


In [8]:
#Split into train and test

X_train, X_test, y_train, y_test= train_test_split(X, y, test_size = 0.4, random_state = 70, stratify= y)

# Show the results of the split
print ("Training set has {} samples.".format(X_train.shape[0]))
print ("Testing set has {} samples.".format(X_test.shape[0]))

Training set has 43335 samples.
Testing set has 28891 samples.


In [9]:
numerical = [col for col in X if X.dtypes[col] == "float64"]
numerical

['loan_amnt',
 'term',
 'int_rate',
 'installment',
 'annual_inc',
 'dti',
 'open_acc',
 'revol_bal',
 'pub_rec_bankruptcies']

In [10]:
#### skalieren
from sklearn.preprocessing import MinMaxScaler


# Initialize a scaler, then apply it to the features
scaler = MinMaxScaler()
#numerical = ['loan_amnt', 'term', 'int_rate', 'installment', 'annual_inc',"issue_d","dti","open_acc","revol_bal","pub_rec_bankruptcies" ]
numerical = [col for col in X if X.dtypes[col] == "float64"]
X_train.loc[:,numerical] = scaler.fit_transform(X_train[numerical])
X_test.loc[:,numerical] = scaler.transform(X_test[numerical])



/Users/kli/neuefische/13_Decision_trees/ds-ensemble-methods/.venv/lib/python3.8/site-packages/pandas/core/indexing.py:1738: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value[:, i].tolist(), pi)
/Users/kli/neuefische/13_Decision_trees/ds-ensemble-methods/.venv/lib/python3.8/site-packages/pandas/core/indexing.py:1738: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value[:, i].tolist(), pi)


In [11]:
X_train.isna().sum()

loan_amnt                              0
term                                   0
int_rate                               0
installment                            0
annual_inc                             0
issue_d                                0
dti                                    0
open_acc                               0
revol_bal                              0
pub_rec_bankruptcies                   0
grade_B                                0
grade_C                                0
grade_D                                0
grade_E                                0
grade_F                                0
grade_G                                0
emp_length_10+ years                   0
emp_length_2 years                     0
emp_length_3 years                     0
emp_length_4 years                     0
emp_length_5 years                     0
emp_length_6 years                     0
emp_length_7 years                     0
emp_length_8 years                     0
emp_length_9 yea

In [12]:
####fit von log reg

lr = LogisticRegression(max_iter=10000,random_state=70)
lr.fit(X_train, y_train)
lr.score(X_train,y_train)

0.5000115380177685

In [13]:
### predic

y_pred = lr.predict(X_test)

In [14]:
### score für unsere trainingsdaten

score_print(y_train,lr.predict(X_train))

[[    0 21667]
 [    0 21668]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00     21667
           1       0.50      1.00      0.67     21668

    accuracy                           0.50     43335
   macro avg       0.25      0.50      0.33     43335
weighted avg       0.25      0.50      0.33     43335

/Users/kli/neuefische/13_Decision_trees/ds-ensemble-methods/.venv/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/kli/neuefische/13_Decision_trees/ds-ensemble-methods/.venv/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` p

In [15]:
#####evu

score_print(y_test,y_pred)

[[    0 14446]
 [    0 14445]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00     14446
           1       0.50      1.00      0.67     14445

    accuracy                           0.50     28891
   macro avg       0.25      0.50      0.33     28891
weighted avg       0.25      0.50      0.33     28891

/Users/kli/neuefische/13_Decision_trees/ds-ensemble-methods/.venv/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/kli/neuefische/13_Decision_trees/ds-ensemble-methods/.venv/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` p

In [16]:
######## DecisionTree
dtc = DecisionTreeClassifier(max_depth=10, min_samples_split=5, random_state=70)
dtc.fit(X_train,y_train)
y_pred_dtc=dtc.predict(X_test)
score_print(y_test,y_pred_dtc)

[[12977  1469]
 [ 2929 11516]]
              precision    recall  f1-score   support

           0       0.82      0.90      0.86     14446
           1       0.89      0.80      0.84     14445

    accuracy                           0.85     28891
   macro avg       0.85      0.85      0.85     28891
weighted avg       0.85      0.85      0.85     28891



In [17]:
### score auf unsere trainingdaten


score_print(y_train,dtc.predict(X_train))

[[19880  1787]
 [ 3760 17908]]
              precision    recall  f1-score   support

           0       0.84      0.92      0.88     21667
           1       0.91      0.83      0.87     21668

    accuracy                           0.87     43335
   macro avg       0.88      0.87      0.87     43335
weighted avg       0.88      0.87      0.87     43335



In [18]:
X_train.shape

(43335, 46)

In [19]:
y_train.shape

(43335,)

In [20]:
####LinearSVC

In [21]:
svc= LinearSVC(random_state=70)
svc.fit(X_train,y_train)
y_pred_svc=dtc.predict(X_test)
score_print(y_test,y_pred_svc)

[[12977  1469]
 [ 2929 11516]]
              precision    recall  f1-score   support

           0       0.82      0.90      0.86     14446
           1       0.89      0.80      0.84     14445

    accuracy                           0.85     28891
   macro avg       0.85      0.85      0.85     28891
weighted avg       0.85      0.85      0.85     28891

/Users/kli/neuefische/13_Decision_trees/ds-ensemble-methods/.venv/lib/python3.8/site-packages/sklearn/svm/_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "


In [22]:
########## score auf unsere trainingdaten


score_print(y_train,svc.predict(X_train))

[[    0 21667]
 [    0 21668]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00     21667
           1       0.50      1.00      0.67     21668

    accuracy                           0.50     43335
   macro avg       0.25      0.50      0.33     43335
weighted avg       0.25      0.50      0.33     43335

/Users/kli/neuefische/13_Decision_trees/ds-ensemble-methods/.venv/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/kli/neuefische/13_Decision_trees/ds-ensemble-methods/.venv/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` p

In [23]:
#######   KNeighborsClassifier

In [24]:
knn=KNeighborsClassifier(n_neighbors=5)

knn.fit(X_train,y_train)
y_pred_knn=knn.predict(X_test)
score_print(y_test,y_pred_knn)

[[13321  1125]
 [ 2464 11981]]
              precision    recall  f1-score   support

           0       0.84      0.92      0.88     14446
           1       0.91      0.83      0.87     14445

    accuracy                           0.88     28891
   macro avg       0.88      0.88      0.88     28891
weighted avg       0.88      0.88      0.88     28891



In [25]:
########## score auf unsere trainingdaten


score_print(y_train,knn.predict(X_train))

[[20767   900]
 [ 3070 18598]]
              precision    recall  f1-score   support

           0       0.87      0.96      0.91     21667
           1       0.95      0.86      0.90     21668

    accuracy                           0.91     43335
   macro avg       0.91      0.91      0.91     43335
weighted avg       0.91      0.91      0.91     43335



In [26]:
###### svm

clf = svm.SVC(kernel='rbf')
#clf.fit(X_train,y_train)
#y_pred_clf=clf.predict(X_test)
#score_print(y_test,y_pred_clf)

In [27]:
########## score auf unsere trainingdaten


#score_print(y_train,clf.predict(X_train))

In [28]:
##### RandomForestClassifier

rfc= RandomForestClassifier(max_depth=5,min_samples_split=20)
rfc.fit(X_train,y_train)
y_pred_rfc=rfc.predict(X_test)
score_print(y_test,y_pred_rfc)

[[12051  2395]
 [ 2861 11584]]
              precision    recall  f1-score   support

           0       0.81      0.83      0.82     14446
           1       0.83      0.80      0.82     14445

    accuracy                           0.82     28891
   macro avg       0.82      0.82      0.82     28891
weighted avg       0.82      0.82      0.82     28891



In [29]:
########## score auf unsere trainingdaten


score_print(y_train,rfc.predict(X_train))

[[18142  3525]
 [ 4321 17347]]
              precision    recall  f1-score   support

           0       0.81      0.84      0.82     21667
           1       0.83      0.80      0.82     21668

    accuracy                           0.82     43335
   macro avg       0.82      0.82      0.82     43335
weighted avg       0.82      0.82      0.82     43335



In [30]:
%store X_train X_test y_test y_train score_print

Stored 'X_train' (DataFrame)
Stored 'X_test' (DataFrame)
Stored 'y_test' (Series)
Stored 'y_train' (Series)
Proper storage of interactively declared classes (or instances
of those classes) is not possible! Only instances
of classes in real modules on file system can be %store'd.

