In [52]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import svm



from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import LinearSVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, classification_report

%store -r X y

In [27]:
##### Funktion scor


def score_print(y,y_pred):
    
    cm = confusion_matrix(y,y_pred)
    print(cm)
    cp= classification_report(y,y_pred)
    print(cp)
    

In [28]:
###### Naiv-estimator


# TODO: Total number of records
n_records = len(X)

# TODO: Number of records where individual's income is more than $50,000
fully_paid = y.sum()

# TODO: Number of records where individual's income is at most $50,000
charged_off = n_records - fully_paid

# TODO: Percentage of individuals whose income is more than $50,000
greater_percent = 100 * fully_paid / n_records

# Print the results
print ("Total number of records: {}".format(n_records))
print ("Individuals has paid her credit fully: {}".format(fully_paid))
print ("Individuals hasn't paid her credit: {}".format(charged_off))
print ("Percentage of individuals that paid ther credit: {:.2f}%".format(greater_percent))

Total number of records: 42535
Individuals has paid her credit fully: 33136
Individuals hasn't paid her credit: 9399
Percentage of individuals that paid ther credit: 77.90%


In [5]:
#Split into train and test

X_train, X_test, y_train, y_test= train_test_split(X, y, test_size = 0.4, random_state = 70, stratify= y)

# Show the results of the split
print ("Training set has {} samples.".format(X_train.shape[0]))
print ("Testing set has {} samples.".format(X_test.shape[0]))

Training set has 25521 samples.
Testing set has 17014 samples.


In [78]:
#### skalieren
from sklearn.preprocessing import MinMaxScaler


# Initialize a scaler, then apply it to the features
scaler = MinMaxScaler()
numerical = ['loan_amnt', 'term', 'int_rate', 'installment', 'annual_inc',"issue_d","dti","open_acc","revol_bal","pub_rec_bankruptcies" ]
X_train.loc[:,numerical] = scaler.fit_transform(X_train[numerical])
X_test.loc[:,numerical] = scaler.transform(X_test[numerical])



/Users/yusufcan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/pandas/core/indexing.py:1738: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value[:, i].tolist(), pi)
/Users/yusufcan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/pandas/core/indexing.py:1738: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value[:, i].tolist(), pi)


In [79]:
####fit von log reg

lr = LogisticRegression(max_iter=10000,random_state=70)
lr.fit(X_train, y_train)
lr.score(X_train,y_train)

0.7888405626738764

In [9]:
### predic

y_pred = lr.predict(X_test)

In [32]:
### score für unsere trainingsdaten

score_print(y_train,lr.predict(X_train))

[[  796  4843]
 [  546 19336]]
              precision    recall  f1-score   support

           0       0.59      0.14      0.23      5639
           1       0.80      0.97      0.88     19882

    accuracy                           0.79     25521
   macro avg       0.70      0.56      0.55     25521
weighted avg       0.75      0.79      0.73     25521



In [29]:
#####evu

score_print(y_test,y_pred)

[[  523  3237]
 [  384 12870]]
              precision    recall  f1-score   support

           0       0.58      0.14      0.22      3760
           1       0.80      0.97      0.88     13254

    accuracy                           0.79     17014
   macro avg       0.69      0.56      0.55     17014
weighted avg       0.75      0.79      0.73     17014



In [30]:
######## DecisionTree
dtc = DecisionTreeClassifier(max_depth=10, min_samples_split=5, random_state=70)
dtc.fit(X_train,y_train)
y_pred_dtc=dtc.predict(X_test)
score_print(y_test,y_pred_dtc)

[[  897  2863]
 [  702 12552]]
              precision    recall  f1-score   support

           0       0.56      0.24      0.33      3760
           1       0.81      0.95      0.88     13254

    accuracy                           0.79     17014
   macro avg       0.69      0.59      0.61     17014
weighted avg       0.76      0.79      0.76     17014



In [31]:
### score auf unsere trainingdaten


score_print(y_train,dtc.predict(X_train))

[[ 1843  3796]
 [  541 19341]]
              precision    recall  f1-score   support

           0       0.77      0.33      0.46      5639
           1       0.84      0.97      0.90     19882

    accuracy                           0.83     25521
   macro avg       0.80      0.65      0.68     25521
weighted avg       0.82      0.83      0.80     25521



In [25]:
X_train.shape

(25521, 40)

In [26]:
y_train.shape

(25521,)

In [ ]:
####LinearSVC

In [42]:
svc= LinearSVC(random_state=70)
svc.fit(X_train,y_train)
y_pred_svc=dtc.predict(X_test)
score_print(y_test,y_pred_svc)

[[  897  2863]
 [  702 12552]]
              precision    recall  f1-score   support

           0       0.56      0.24      0.33      3760
           1       0.81      0.95      0.88     13254

    accuracy                           0.79     17014
   macro avg       0.69      0.59      0.61     17014
weighted avg       0.76      0.79      0.76     17014



In [35]:
########## score auf unsere trainingdaten


score_print(y_train,svc.predict(X_train))

[[  425  5214]
 [  218 19664]]
              precision    recall  f1-score   support

           0       0.66      0.08      0.14      5639
           1       0.79      0.99      0.88     19882

    accuracy                           0.79     25521
   macro avg       0.73      0.53      0.51     25521
weighted avg       0.76      0.79      0.71     25521



In [ ]:
#######   KNeighborsClassifier

In [66]:
knn=KNeighborsClassifier(n_neighbors=5)

knn.fit(X_train,y_train)
y_pred_knn=knn.predict(X_test)
score_print(y_test,y_pred_knn)

[[  694  3066]
 [ 1018 12236]]
              precision    recall  f1-score   support

           0       0.41      0.18      0.25      3760
           1       0.80      0.92      0.86     13254

    accuracy                           0.76     17014
   macro avg       0.60      0.55      0.56     17014
weighted avg       0.71      0.76      0.72     17014



In [59]:
########## score auf unsere trainingdaten


score_print(y_train,knn.predict(X_train))

[[ 1960  3679]
 [  812 19070]]
              precision    recall  f1-score   support

           0       0.71      0.35      0.47      5639
           1       0.84      0.96      0.89     19882

    accuracy                           0.82     25521
   macro avg       0.77      0.65      0.68     25521
weighted avg       0.81      0.82      0.80     25521



In [68]:
###### svm

clf = svm.SVC(kernel='rbf')
clf.fit(X_train,y_train)
y_pred_clf=clf.predict(X_test)
score_print(y_test,y_pred_clf)

[[  142  3618]
 [   24 13230]]
              precision    recall  f1-score   support

           0       0.86      0.04      0.07      3760
           1       0.79      1.00      0.88     13254

    accuracy                           0.79     17014
   macro avg       0.82      0.52      0.48     17014
weighted avg       0.80      0.79      0.70     17014



In [60]:
########## score auf unsere trainingdaten


score_print(y_train,clf.predict(X_train))

[[  273  5366]
 [   19 19863]]
              precision    recall  f1-score   support

           0       0.93      0.05      0.09      5639
           1       0.79      1.00      0.88     19882

    accuracy                           0.79     25521
   macro avg       0.86      0.52      0.49     25521
weighted avg       0.82      0.79      0.71     25521



In [73]:
##### RandomForestClassifier

rfc= RandomForestClassifier(max_depth=5,min_samples_split=20)
rfc.fit(X_train,y_train)
y_pred_rfc=rfc.predict(X_test)
score_print(y_test,y_pred_rfc)

[[  105  3655]
 [    4 13250]]
              precision    recall  f1-score   support

           0       0.96      0.03      0.05      3760
           1       0.78      1.00      0.88     13254

    accuracy                           0.78     17014
   macro avg       0.87      0.51      0.47     17014
weighted avg       0.82      0.78      0.70     17014



In [74]:
########## score auf unsere trainingdaten


score_print(y_train,rfc.predict(X_train))

[[  193  5446]
 [    1 19881]]
              precision    recall  f1-score   support

           0       0.99      0.03      0.07      5639
           1       0.78      1.00      0.88     19882

    accuracy                           0.79     25521
   macro avg       0.89      0.52      0.47     25521
weighted avg       0.83      0.79      0.70     25521



In [84]:
%store X_train X_test y_test y_train score_print

Stored 'X_train' (DataFrame)
Stored 'X_test' (DataFrame)
Stored 'y_test' (Series)
Stored 'y_train' (Series)
Proper storage of interactively declared classes (or instances
of those classes) is not possible! Only instances
of classes in real modules on file system can be %store'd.

