In [43]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import svm



from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import LinearSVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, classification_report

%store -r X y
y

0        0
1        0
2        1
3        0
4        0
        ..
21737    1
21738    1
21739    1
21740    1
21741    1
Name: loan_status_int, Length: 21742, dtype: int64

In [44]:
##### Funktion scor


def score_print(y,y_pred):
    
    cm = confusion_matrix(y,y_pred)
    print(cm)
    cp= classification_report(y,y_pred)
    print(cp)
    

In [45]:
###### Naiv-estimator


# TODO: Total number of records
n_records = len(X)

# TODO: Number of records where individual's income is more than $50,000
fully_paid = sum(y==1)

# TODO: Number of records where individual's income is at most $50,000
charged_off = n_records - fully_paid

# TODO: Percentage of individuals whose income is more than $50,000
greater_percent = 100 * fully_paid / n_records

# Print the results
print ("Total number of records: {}".format(n_records))
print ("Individuals has paid her credit fully: {}".format(fully_paid))
print ("Individuals hasn't paid her credit: {}".format(charged_off))
print ("Percentage of individuals that paid ther credit: {:.2f}%".format(greater_percent))

Total number of records: 21742
Individuals has paid her credit fully: 10871
Individuals hasn't paid her credit: 10871
Percentage of individuals that paid ther credit: 50.00%


In [46]:
#Split into train and test

X_train, X_test, y_train, y_test= train_test_split(X, y, test_size = 0.4, random_state = 70, stratify= y)

# Show the results of the split
print ("Training set has {} samples.".format(X_train.shape[0]))
print ("Testing set has {} samples.".format(X_test.shape[0]))

Training set has 13045 samples.
Testing set has 8697 samples.


In [47]:
numerical = [col for col in X if X.dtypes[col] == "float64"]
numerical

['loan_amnt',
 'term',
 'int_rate',
 'installment',
 'annual_inc',
 'dti',
 'open_acc',
 'revol_bal',
 'pub_rec_bankruptcies']

In [48]:
#### skalieren
from sklearn.preprocessing import MinMaxScaler


# Initialize a scaler, then apply it to the features
scaler = MinMaxScaler()
#numerical = ['loan_amnt', 'term', 'int_rate', 'installment', 'annual_inc',"issue_d","dti","open_acc","revol_bal","pub_rec_bankruptcies" ]
numerical = [col for col in X if X.dtypes[col] == "float64"]
X_train.loc[:,numerical] = scaler.fit_transform(X_train[numerical])
X_test.loc[:,numerical] = scaler.transform(X_test[numerical])



/Users/kli/neuefische/13_Decision_trees/ds-ensemble-methods/.venv/lib/python3.8/site-packages/pandas/core/indexing.py:1738: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value[:, i].tolist(), pi)
/Users/kli/neuefische/13_Decision_trees/ds-ensemble-methods/.venv/lib/python3.8/site-packages/pandas/core/indexing.py:1738: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value[:, i].tolist(), pi)


In [49]:
# import library
from imblearn.over_sampling import SMOTE

smote = SMOTE()

# fit predictor and target variable
X_train, y_train = smote.fit_resample(X_train, y_train)

print('Original dataset shape', y.sum())
print('Resample dataset shape', y_smote.sum())

loan_amnt                              0
term                                   0
int_rate                               0
installment                            0
annual_inc                             0
issue_d                                0
dti                                    0
open_acc                               0
revol_bal                              0
pub_rec_bankruptcies                   0
emp_length_10+ years                   0
emp_length_2 years                     0
emp_length_3 years                     0
emp_length_4 years                     0
emp_length_5 years                     0
emp_length_6 years                     0
emp_length_7 years                     0
emp_length_8 years                     0
emp_length_9 years                     0
emp_length_< 1 year                    0
emp_length_no info at all              0
home_ownership_NONE                    0
home_ownership_OTHER                   0
home_ownership_OWN                     0
home_ownership_R

In [50]:
####fit von log reg

lr = LogisticRegression(max_iter=10000,random_state=70)
lr.fit(X_train, y_train)
lr.score(X_train,y_train)

0.5000383288616328

In [51]:
### predic

y_pred = lr.predict(X_test)

In [52]:
### score für unsere trainingsdaten

score_print(y_train,lr.predict(X_train))

[[   0 6522]
 [   0 6523]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00      6522
           1       0.50      1.00      0.67      6523

    accuracy                           0.50     13045
   macro avg       0.25      0.50      0.33     13045
weighted avg       0.25      0.50      0.33     13045

/Users/kli/neuefische/13_Decision_trees/ds-ensemble-methods/.venv/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/kli/neuefische/13_Decision_trees/ds-ensemble-methods/.venv/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` param

In [53]:
#####evu

score_print(y_test,y_pred)

[[   0 4349]
 [   0 4348]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00      4349
           1       0.50      1.00      0.67      4348

    accuracy                           0.50      8697
   macro avg       0.25      0.50      0.33      8697
weighted avg       0.25      0.50      0.33      8697

/Users/kli/neuefische/13_Decision_trees/ds-ensemble-methods/.venv/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/kli/neuefische/13_Decision_trees/ds-ensemble-methods/.venv/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` param

In [54]:
######## DecisionTree
dtc = DecisionTreeClassifier(max_depth=10, min_samples_split=5, random_state=70)
dtc.fit(X_train,y_train)
y_pred_dtc=dtc.predict(X_test)
score_print(y_test,y_pred_dtc)

[[3629  720]
 [ 672 3676]]
              precision    recall  f1-score   support

           0       0.84      0.83      0.84      4349
           1       0.84      0.85      0.84      4348

    accuracy                           0.84      8697
   macro avg       0.84      0.84      0.84      8697
weighted avg       0.84      0.84      0.84      8697



In [55]:
### score auf unsere trainingdaten


score_print(y_train,dtc.predict(X_train))

[[5688  834]
 [ 734 5789]]
              precision    recall  f1-score   support

           0       0.89      0.87      0.88      6522
           1       0.87      0.89      0.88      6523

    accuracy                           0.88     13045
   macro avg       0.88      0.88      0.88     13045
weighted avg       0.88      0.88      0.88     13045



In [56]:
X_train.shape

(13045, 40)

In [42]:
y_train.shape

(11487,)

In [17]:
####LinearSVC

In [18]:
svc= LinearSVC(random_state=70)
svc.fit(X_train,y_train)
y_pred_svc=dtc.predict(X_test)
score_print(y_test,y_pred_svc)

[[2206  690]
 [ 570 2325]]
              precision    recall  f1-score   support

           0       0.79      0.76      0.78      2896
           1       0.77      0.80      0.79      2895

    accuracy                           0.78      5791
   macro avg       0.78      0.78      0.78      5791
weighted avg       0.78      0.78      0.78      5791

/Users/kli/neuefische/13_Decision_trees/ds-ensemble-methods/.venv/lib/python3.8/site-packages/sklearn/svm/_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "


In [19]:
########## score auf unsere trainingdaten


score_print(y_train,svc.predict(X_train))

[[4342    0]
 [4343    0]]
              precision    recall  f1-score   support

           0       0.50      1.00      0.67      4342
           1       0.00      0.00      0.00      4343

    accuracy                           0.50      8685
   macro avg       0.25      0.50      0.33      8685
weighted avg       0.25      0.50      0.33      8685

/Users/kli/neuefische/13_Decision_trees/ds-ensemble-methods/.venv/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/kli/neuefische/13_Decision_trees/ds-ensemble-methods/.venv/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` param

In [20]:
#######   KNeighborsClassifier

In [21]:
knn=KNeighborsClassifier(n_neighbors=5)

knn.fit(X_train,y_train)
y_pred_knn=knn.predict(X_test)
score_print(y_test,y_pred_knn)

[[2515  381]
 [ 562 2333]]
              precision    recall  f1-score   support

           0       0.82      0.87      0.84      2896
           1       0.86      0.81      0.83      2895

    accuracy                           0.84      5791
   macro avg       0.84      0.84      0.84      5791
weighted avg       0.84      0.84      0.84      5791



In [22]:
########## score auf unsere trainingdaten


score_print(y_train,knn.predict(X_train))

[[4023  319]
 [ 709 3634]]
              precision    recall  f1-score   support

           0       0.85      0.93      0.89      4342
           1       0.92      0.84      0.88      4343

    accuracy                           0.88      8685
   macro avg       0.88      0.88      0.88      8685
weighted avg       0.88      0.88      0.88      8685



In [23]:
###### svm

clf = svm.SVC(kernel='rbf')
#clf.fit(X_train,y_train)
#y_pred_clf=clf.predict(X_test)
#score_print(y_test,y_pred_clf)

In [24]:
########## score auf unsere trainingdaten


#score_print(y_train,clf.predict(X_train))

In [25]:
##### RandomForestClassifier

rfc= RandomForestClassifier(max_depth=5,min_samples_split=20)
rfc.fit(X_train,y_train)
y_pred_rfc=rfc.predict(X_test)
score_print(y_test,y_pred_rfc)

[[2436  460]
 [ 678 2217]]
              precision    recall  f1-score   support

           0       0.78      0.84      0.81      2896
           1       0.83      0.77      0.80      2895

    accuracy                           0.80      5791
   macro avg       0.81      0.80      0.80      5791
weighted avg       0.81      0.80      0.80      5791



In [26]:
########## score auf unsere trainingdaten


score_print(y_train,rfc.predict(X_train))

[[3688  654]
 [1021 3322]]
              precision    recall  f1-score   support

           0       0.78      0.85      0.81      4342
           1       0.84      0.76      0.80      4343

    accuracy                           0.81      8685
   macro avg       0.81      0.81      0.81      8685
weighted avg       0.81      0.81      0.81      8685



In [27]:
%store X_train X_test y_test y_train score_print

Stored 'X_train' (DataFrame)
Stored 'X_test' (DataFrame)
Stored 'y_test' (Series)
Stored 'y_train' (Series)
Proper storage of interactively declared classes (or instances
of those classes) is not possible! Only instances
of classes in real modules on file system can be %store'd.

