In [17]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import svm



from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import LinearSVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, classification_report

%store -r X y
X

loan_amnt       term   int_rate  installment    annual_inc  issue_d  \
0       5000.000000  36.000000  10.650000   162.870000  24000.000000   734472   
1       2500.000000  60.000000  15.270000    59.830000  30000.000000   734472   
2       2400.000000  36.000000  15.960000    84.330000  12252.000000   734472   
3      10000.000000  36.000000  13.490000   339.310000  49200.000000   734472   
4       3000.000000  60.000000  12.690000    67.790000  80000.000000   734472   
...             ...        ...        ...          ...           ...      ...   
72221  15000.000000  51.199318  10.111371   373.444459  43860.051160   733764   
72222   2538.877576  41.555103  17.318447    83.355886  30922.244848   734312   
72223  14115.713547  36.000000  14.379711   486.081659  90263.266361   734145   
72224  15790.018128  36.000000  15.600163   553.170729  95125.989123   734343   
72225   2500.000000  36.000000   9.945049    80.642027  22979.160821   733007   

             dti   open_acc     revol_bal  pub_rec_bankruptcies  ...  \
0      27.650000   3.000000  13648.000000              0.000000  ...   
1       1.000000   3.000000   1687.000000              0.000000  ...   
2       8.720000   2.000000   2956.000000              0.000000  ...   
3      20.000000  10.000000   5598.000000              0.000000  ...   
4      17.940000  15.000000  27783.000000              0.000000  ...   
...          ...        ...           ...                   ...  ...   
72221   1.171674   3.633305   1039.094577              0.366695  ...   
72222  10.182370   4.462925   5090.705438              0.000000  ...   
72223  10.503972   3.368367   1129.721794              0.000000  ...   
72224  18.851984   8.049909   9160.507093              0.000000  ...   
72225   2.107975   2.456592    965.620729              0.000000  ...   

       purpose_home_improvement  purpose_house  purpose_major_purchase  \
0                             0              0                       0   
1                             0              0                       0   
2                             0              0                       0   
3                             0              0                       0   
4                             0              0                       0   
...                         ...            ...                     ...   
72221                         0              0                       0   
72222                         0              0                       0   
72223                         0              0                       0   
72224                         0              0                       0   
72225                         0              0                       0   

       purpose_medical  purpose_moving  purpose_other  \
0                    0               0              0   
1                    0               0              0   
2                    0               0              0   
3                    0               0              1   
4                    0               0              1   
...                ...             ...            ...   
72221                0               0              0   
72222                0               0              0   
72223                0               0              0   
72224                0               0              0   
72225                0               0              0   

       purpose_renewable_energy  purpose_small_business  purpose_vacation  \
0                             0                       0                 0   
1                             0                       0                 0   
2                             0                       1                 0   
3                             0                       0                 0   
4                             0                       0                 0   
...                         ...                     ...               ...   
72221                         0                       0    

In [18]:
##### Funktion scor


def score_print(y,y_pred):
    
    cm = confusion_matrix(y,y_pred)
    print(cm)
    cp= classification_report(y,y_pred)
    print(cp)
    

In [20]:
###### Naiv-estimator


# TODO: Total number of records
n_records = len(X)

# TODO: Number of records where individual's income is more than $50,000
fully_paid = sum(y==1)

# TODO: Number of records where individual's income is at most $50,000
charged_off = n_records - fully_paid

# TODO: Percentage of individuals whose income is more than $50,000
greater_percent = 100 * fully_paid / n_records

# Print the results
print ("Total number of records: {}".format(n_records))
print ("Individuals has paid her credit fully: {}".format(fully_paid))
print ("Individuals hasn't paid her credit: {}".format(charged_off))
print ("Percentage of individuals that paid ther credit: {:.2f}%".format(greater_percent))

Total number of records: 72226
Individuals has paid her credit fully: 36113
Individuals hasn't paid her credit: 36113
Percentage of individuals that paid ther credit: 50.00%


In [21]:
#Split into train and test

X_train, X_test, y_train, y_test= train_test_split(X, y, test_size = 0.4, random_state = 70, stratify= y)

# Show the results of the split
print ("Training set has {} samples.".format(X_train.shape[0]))
print ("Testing set has {} samples.".format(X_test.shape[0]))

Training set has 43335 samples.
Testing set has 28891 samples.


In [22]:
numerical = [col for col in X if X.dtypes[col] == "float64"]
numerical

['loan_amnt',
 'term',
 'int_rate',
 'installment',
 'annual_inc',
 'dti',
 'open_acc',
 'revol_bal',
 'pub_rec_bankruptcies']

In [23]:
#### skalieren
from sklearn.preprocessing import MinMaxScaler


# Initialize a scaler, then apply it to the features
scaler = MinMaxScaler()
#numerical = ['loan_amnt', 'term', 'int_rate', 'installment', 'annual_inc',"issue_d","dti","open_acc","revol_bal","pub_rec_bankruptcies" ]
numerical = [col for col in X if X.dtypes[col] == "float64"]
X_train.loc[:,numerical] = scaler.fit_transform(X_train[numerical])
X_test.loc[:,numerical] = scaler.transform(X_test[numerical])



/Users/kli/neuefische/13_Decision_trees/ds-ensemble-methods/.venv/lib/python3.8/site-packages/pandas/core/indexing.py:1738: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value[:, i].tolist(), pi)
/Users/kli/neuefische/13_Decision_trees/ds-ensemble-methods/.venv/lib/python3.8/site-packages/pandas/core/indexing.py:1738: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value[:, i].tolist(), pi)


In [24]:
X_train.isna().sum()

loan_amnt                              0
term                                   0
int_rate                               0
installment                            0
annual_inc                             0
issue_d                                0
dti                                    0
open_acc                               0
revol_bal                              0
pub_rec_bankruptcies                   0
emp_length_10+ years                   0
emp_length_2 years                     0
emp_length_3 years                     0
emp_length_4 years                     0
emp_length_5 years                     0
emp_length_6 years                     0
emp_length_7 years                     0
emp_length_8 years                     0
emp_length_9 years                     0
emp_length_< 1 year                    0
emp_length_no info at all              0
home_ownership_NONE                    0
home_ownership_OTHER                   0
home_ownership_OWN                     0
home_ownership_R

In [25]:
####fit von log reg

lr = LogisticRegression(max_iter=10000,random_state=70)
lr.fit(X_train, y_train)
lr.score(X_train,y_train)

0.5000115380177685

In [26]:
### predic

y_pred = lr.predict(X_test)

In [27]:
### score für unsere trainingsdaten

score_print(y_train,lr.predict(X_train))

[[    0 21667]
 [    0 21668]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00     21667
           1       0.50      1.00      0.67     21668

    accuracy                           0.50     43335
   macro avg       0.25      0.50      0.33     43335
weighted avg       0.25      0.50      0.33     43335

/Users/kli/neuefische/13_Decision_trees/ds-ensemble-methods/.venv/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/kli/neuefische/13_Decision_trees/ds-ensemble-methods/.venv/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` p

In [28]:
#####evu

score_print(y_test,y_pred)

[[    0 14446]
 [    0 14445]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00     14446
           1       0.50      1.00      0.67     14445

    accuracy                           0.50     28891
   macro avg       0.25      0.50      0.33     28891
weighted avg       0.25      0.50      0.33     28891

/Users/kli/neuefische/13_Decision_trees/ds-ensemble-methods/.venv/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/kli/neuefische/13_Decision_trees/ds-ensemble-methods/.venv/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` p

In [29]:
######## DecisionTree
dtc = DecisionTreeClassifier(max_depth=10, min_samples_split=5, random_state=70)
dtc.fit(X_train,y_train)
y_pred_dtc=dtc.predict(X_test)
score_print(y_test,y_pred_dtc)

[[12166  2280]
 [ 3028 11417]]
              precision    recall  f1-score   support

           0       0.80      0.84      0.82     14446
           1       0.83      0.79      0.81     14445

    accuracy                           0.82     28891
   macro avg       0.82      0.82      0.82     28891
weighted avg       0.82      0.82      0.82     28891



In [30]:
### score auf unsere trainingdaten


score_print(y_train,dtc.predict(X_train))

[[18711  2956]
 [ 4042 17626]]
              precision    recall  f1-score   support

           0       0.82      0.86      0.84     21667
           1       0.86      0.81      0.83     21668

    accuracy                           0.84     43335
   macro avg       0.84      0.84      0.84     43335
weighted avg       0.84      0.84      0.84     43335



In [31]:
X_train.shape

(43335, 40)

In [32]:
y_train.shape

(43335,)

In [33]:
####LinearSVC

In [34]:
svc= LinearSVC(random_state=70)
svc.fit(X_train,y_train)
y_pred_svc=dtc.predict(X_test)
score_print(y_test,y_pred_svc)

[[12166  2280]
 [ 3028 11417]]
              precision    recall  f1-score   support

           0       0.80      0.84      0.82     14446
           1       0.83      0.79      0.81     14445

    accuracy                           0.82     28891
   macro avg       0.82      0.82      0.82     28891
weighted avg       0.82      0.82      0.82     28891

/Users/kli/neuefische/13_Decision_trees/ds-ensemble-methods/.venv/lib/python3.8/site-packages/sklearn/svm/_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "


In [35]:
########## score auf unsere trainingdaten


score_print(y_train,svc.predict(X_train))

[[    0 21667]
 [    0 21668]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00     21667
           1       0.50      1.00      0.67     21668

    accuracy                           0.50     43335
   macro avg       0.25      0.50      0.33     43335
weighted avg       0.25      0.50      0.33     43335

/Users/kli/neuefische/13_Decision_trees/ds-ensemble-methods/.venv/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/kli/neuefische/13_Decision_trees/ds-ensemble-methods/.venv/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` p

In [36]:
#######   KNeighborsClassifier

In [37]:
knn=KNeighborsClassifier(n_neighbors=5)

knn.fit(X_train,y_train)
y_pred_knn=knn.predict(X_test)
score_print(y_test,y_pred_knn)

[[13290  1156]
 [ 2562 11883]]
              precision    recall  f1-score   support

           0       0.84      0.92      0.88     14446
           1       0.91      0.82      0.86     14445

    accuracy                           0.87     28891
   macro avg       0.87      0.87      0.87     28891
weighted avg       0.87      0.87      0.87     28891



In [38]:
########## score auf unsere trainingdaten


score_print(y_train,knn.predict(X_train))

[[20722   945]
 [ 3140 18528]]
              precision    recall  f1-score   support

           0       0.87      0.96      0.91     21667
           1       0.95      0.86      0.90     21668

    accuracy                           0.91     43335
   macro avg       0.91      0.91      0.91     43335
weighted avg       0.91      0.91      0.91     43335



In [39]:
###### svm

clf = svm.SVC(kernel='rbf')
#clf.fit(X_train,y_train)
#y_pred_clf=clf.predict(X_test)
#score_print(y_test,y_pred_clf)

In [40]:
########## score auf unsere trainingdaten


#score_print(y_train,clf.predict(X_train))

In [41]:
##### RandomForestClassifier

rfc= RandomForestClassifier(max_depth=5,min_samples_split=20)
rfc.fit(X_train,y_train)
y_pred_rfc=rfc.predict(X_test)
score_print(y_test,y_pred_rfc)

[[11764  2682]
 [ 2951 11494]]
              precision    recall  f1-score   support

           0       0.80      0.81      0.81     14446
           1       0.81      0.80      0.80     14445

    accuracy                           0.81     28891
   macro avg       0.81      0.81      0.81     28891
weighted avg       0.81      0.81      0.81     28891



In [42]:
########## score auf unsere trainingdaten


score_print(y_train,rfc.predict(X_train))

[[17709  3958]
 [ 4320 17348]]
              precision    recall  f1-score   support

           0       0.80      0.82      0.81     21667
           1       0.81      0.80      0.81     21668

    accuracy                           0.81     43335
   macro avg       0.81      0.81      0.81     43335
weighted avg       0.81      0.81      0.81     43335



In [43]:
%store X_train X_test y_test y_train score_print

Stored 'X_train' (DataFrame)
Stored 'X_test' (DataFrame)
Stored 'y_test' (Series)
Stored 'y_train' (Series)
Proper storage of interactively declared classes (or instances
of those classes) is not possible! Only instances
of classes in real modules on file system can be %store'd.

